window.GROGGY_CLIMBS = [
    {
        name: "Willy Wonka",
        grade: "5.11a",
        gradeRank: 22,
        location: "Red River Gorge, KY",
        area: "Chocolate Factory",
        relevance: "Peak Match",
        relevanceRank: 5,
        note: "A logical next step in a zone he already likes, with enough bite to feel real but still sendable.",
        tags: ["Sport", "Steep-ish but manageable"],
        link: "https://www.mountainproject.com/route/108749213/willy-wonka",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Season of the Storm",
        grade: "5.10a",
        gradeRank: 18,
        location: "Horseshoe Canyon Ranch, AR",
        area: "North Forty Routes",
        relevance: "Strong Match",
        relevanceRank: 4,
        note: "An immediate HCR fit for a solid day route without turning into a project.",
        tags: ["Sport", "Vertical"],
        link: "https://www.mountainproject.com/area/classics/105903004/horseshoe-canyon-ranch",
        linkLabel: "View area listing",
        projectPick: false
    },
    {
        name: "Sour Girl",
        grade: "5.10b",
        gradeRank: 19,
        location: "Horseshoe Canyon Ranch, AR",
        area: "North Forty Routes",
        relevance: "Strong Match",
        relevanceRank: 4,
        note: "Right in the sweet spot for a few serious attempts without crossing into full project territory.",
        tags: ["Sport", "Face climbing"],
        link: "https://www.mountainproject.com/area/classics/105903004/horseshoe-canyon-ranch",
        linkLabel: "View area listing",
        projectPick: false
    },
    {
        name: "Sonny Jim",
        grade: "5.11a",
        gradeRank: 22,
        location: "Horseshoe Canyon Ranch, AR",
        area: "North Forty Routes",
        relevance: "Strong Match",
        relevanceRank: 4,
        note: "A very plausible harder send-level HCR route if he wants something just above comfort grade.",
        tags: ["Sport", "HCR"],
        link: "https://www.mountainproject.com/route/105970892/sonny-jim",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Needles and Pins",
        grade: "5.10a",
        gradeRank: 18,
        location: "Red Wing, MN",
        area: "Red Wing",
        relevance: "Strong Match",
        relevanceRank: 4,
        note: "A clean local fit if he wants something very much in range with technical movement rather than steep hauling.",
        tags: ["Sport", "Local-feeling"],
        link: "https://www.mountainproject.com/route/105826285/needles-and-pins",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Frequent Flatulence",
        grade: "5.10b",
        gradeRank: 19,
        location: "Red Wing, MN",
        area: "Red Wing",
        relevance: "Strong Match",
        relevanceRank: 4,
        note: "Right in the range where Garrett should have to fight for it but still reasonably send in a session.",
        tags: ["Sport", "Crimpy"],
        link: "https://www.mountainproject.com/route/105825974/frequent-flatulence",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Hip to the Jive",
        grade: "5.11b",
        gradeRank: 23,
        location: "Red River Gorge, KY",
        area: "Chocolate Factory",
        relevance: "Worth a Shot",
        relevanceRank: 3,
        note: "A bigger stretch if he wants to push above his current high-confidence zone in a familiar area.",
        tags: ["Sport", "Stretch"],
        link: "https://www.mountainproject.com/route/107379148/hip-to-the-jive",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Toxicondendron",
        grade: "5.11b",
        gradeRank: 23,
        location: "Red River Gorge, KY",
        area: "Chocolate Factory",
        relevance: "Worth a Shot",
        relevanceRank: 3,
        note: "Another solid step-up option if he wants to use familiarity with the area to reach a bit higher.",
        tags: ["Sport", "Stretch"],
        link: "https://www.mountainproject.com/route/109695855/toxicondendron",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Big Top",
        grade: "5.11c",
        gradeRank: 24,
        location: "Horseshoe Canyon Ranch, AR",
        area: "North Forty Routes",
        relevance: "Style Borderline",
        relevanceRank: 2,
        note: "A longer-term HCR reach goal, but it sits well beyond the 'few burns' target and is less cleanly matched.",
        tags: ["Sport", "Stretch project"],
        link: "https://www.mountainproject.com/area/classics/105903004/horseshoe-canyon-ranch",
        linkLabel: "View area listing",
        projectPick: false
    },
    {
        name: "Underdog",
        grade: "5.10a",
        gradeRank: 18,
        location: "Rumney, NH",
        area: "Rumney",
        relevance: "Peak Match",
        relevanceRank: 5,
        note: "One of the cleanest nationwide matches: classic sport, in range, and likely to reward a technical approach.",
        tags: ["Sport", "National classic"],
        link: "https://www.mountainproject.com/route/105877217/underdog",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "The Rico Suave Arete",
        grade: "5.10a",
        gradeRank: 18,
        location: "New River Gorge, WV",
        area: "Rico Suave Buttress",
        relevance: "Peak Match",
        relevanceRank: 5,
        note: "A very believable national classic pick if the goal is technical face climbing instead of steep wrestling.",
        tags: ["Sport", "Technical"],
        link: "https://www.mountainproject.com/route/105963848/the-rico-suave-arete-aka-rico-suave",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Strike A Scowl",
        grade: "5.10b",
        gradeRank: 19,
        location: "New River Gorge, WV",
        area: "Diamond Point",
        relevance: "Peak Match",
        relevanceRank: 5,
        note: "One of the clearest style matches in the whole list: technical, not cavey, and right in the attempt band.",
        tags: ["Sport", "Vertical"],
        link: "https://www.mountainproject.com/route/105963042/strike-a-scowl",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Legacy",
        grade: "5.11a",
        gradeRank: 22,
        location: "New River Gorge, WV",
        area: "Snake Buttress",
        relevance: "Strong Match",
        relevanceRank: 4,
        note: "A higher-end fit that could still go in a focused day if he's climbing well and wants a proud line.",
        tags: ["Sport", "Harder option"],
        link: "https://www.mountainproject.com/route/106282216/legacy",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Doob Loob",
        grade: "5.10b",
        gradeRank: 19,
        location: "Wild Iris, WY",
        area: "Wild Iris",
        relevance: "Worth a Shot",
        relevanceRank: 3,
        note: "A reasonable Wild Iris intro, but the area trends more pockety than his ideal style.",
        tags: ["Sport", "Area mismatch"],
        link: "https://www.mountainproject.com/route/106081874/doob-loob",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Winchester Pump",
        grade: "5.11a",
        gradeRank: 22,
        location: "Wild Iris, WY",
        area: "Wild Iris",
        relevance: "Worth a Shot",
        relevanceRank: 3,
        note: "A high-quality option, but still a little outside the perfect no-pockets preference.",
        tags: ["Sport", "Area mismatch"],
        link: "https://www.mountainproject.com/route/105841390/winchester-pump",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Placebo Effect",
        grade: "5.10a",
        gradeRank: 18,
        location: "Obed, TN",
        area: "Y-12",
        relevance: "Strong Match",
        relevanceRank: 4,
        note: "A good nationwide option if he wants something realistic that still feels like a real route, not a warm-up.",
        tags: ["Sport", "Moderately steep"],
        link: "https://www.mountainproject.com/route/112275695/placebo-effect",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Herbivore",
        grade: "5.11a",
        gradeRank: 22,
        location: "Obed, TN",
        area: "Y-12",
        relevance: "Strong Match",
        relevanceRank: 4,
        note: "A good harder option if he wants a little more fight while staying below true project territory.",
        tags: ["Sport", "Harder option"],
        link: "https://www.mountainproject.com/route/106610114/herbivore",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Plea Bargain",
        grade: "5.10a",
        gradeRank: 18,
        location: "Ten Sleep Canyon, WY",
        area: "Home Alone",
        relevance: "Worth a Shot",
        relevanceRank: 3,
        note: "A reasonable Ten Sleep intro, but Ten Sleep as a whole is less aligned with the anti-pocket preference.",
        tags: ["Sport", "Area mismatch"],
        link: "https://www.mountainproject.com/route/105853386/plea-bargain",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Limestoned",
        grade: "5.11a",
        gradeRank: 22,
        location: "Ten Sleep Canyon, WY",
        area: "Home Alone",
        relevance: "Worth a Shot",
        relevanceRank: 3,
        note: "Good if the goal is a trip objective, but still not as style-clean a fit as the New River options.",
        tags: ["Sport", "Trip route"],
        link: "https://www.mountainproject.com/route/105853353/limestoned",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Naxis",
        grade: "5.10b",
        gradeRank: 19,
        location: "Smith Rock, OR",
        area: "Upper Gorge",
        relevance: "Worth a Shot",
        relevanceRank: 3,
        note: "Interesting technical western sport option if he wants something cryptic and less power-based.",
        tags: ["Sport", "Technical"],
        link: "https://www.mountainproject.com/area/105801773/upper-gorge",
        linkLabel: "View area listing",
        projectPick: false
    },
    {
        name: "E-Type Jag",
        grade: "5.11a",
        gradeRank: 22,
        location: "Smith Rock, OR",
        area: "Upper Gorge",
        relevance: "Worth a Shot",
        relevanceRank: 3,
        note: "Another intriguing Smith option if he wants precise technical movement more than raw steep fitness.",
        tags: ["Sport", "Technical"],
        link: "https://www.mountainproject.com/area/105801773/upper-gorge",
        linkLabel: "View area listing",
        projectPick: false
    },
    {
        name: "The Decameron",
        grade: "5.10b",
        gradeRank: 19,
        location: "New River Gorge, WV",
        area: "Sandstonia",
        relevance: "Peak Match",
        relevanceRank: 5,
        note: "Probably the cleanest overall match on the board for vertical face climbing that should go in a handful of tries.",
        tags: ["Sport", "Vertical", "Crimpy"],
        link: "https://www.mountainproject.com/route/106184767/decameron-the",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Sequence of Events",
        grade: "5.10b",
        gradeRank: 19,
        location: "New River Gorge, WV",
        area: "Cotton Club",
        relevance: "Peak Match",
        relevanceRank: 5,
        note: "Exactly the kind of 3-to-4-burn candidate that fits the vertical technical profile instead of steep power climbing.",
        tags: ["Sport", "Vertical", "Crimpy"],
        link: "https://www.mountainproject.com/area/105855991/the-new-river-gorge-region",
        linkLabel: "View area listing",
        projectPick: false
    },
    {
        name: "Kinesthetica",
        grade: "5.10c",
        gradeRank: 20,
        location: "New River Gorge, WV",
        area: "Sandstonia",
        relevance: "Style Borderline",
        relevanceRank: 2,
        note: "Still a real possibility, but the roof section makes it less cleanly aligned with his stated preferences.",
        tags: ["Sport", "Roof move"],
        link: "https://www.mountainproject.com/route/105987545/kinesthetica",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Masuko",
        grade: "5.11a",
        gradeRank: 22,
        location: "Summersville, WV",
        area: "Whippoorwill",
        relevance: "Style Borderline",
        relevanceRank: 2,
        note: "Appealing on paper, but the overhung start makes it less ideal than the flatter New River face routes.",
        tags: ["Sport", "Overhung start"],
        link: "https://www.mountainproject.com/route/106736128/masuko",
        linkLabel: "View route",
        projectPick: false
    },
    {
        name: "Captain Hook",
        grade: "5.12a",
        gradeRank: 25,
        location: "Rumney, NH",
        area: "Rumney",
        relevance: "First 12a Project",
        relevanceRank: 5,
        note: "Best first 12a pick. Tiny holds, technical climbing, and a style that lines up with the crimp-heavy preference.",
        tags: ["Sport", "First 12a", "Technical"],
        link: "https://www.mountainproject.com/route/106033475/captain-hook",
        linkLabel: "View route",
        projectPick: true
    },
    {
        name: "Control",
        grade: "5.12a",
        gradeRank: 25,
        location: "New River Gorge, WV",
        area: "New River Gorge",
        relevance: "First 12a Project",
        relevanceRank: 5,
        note: "Best New River first-12a lane: crimpy enough to fit, with just a bit more mixed terrain than Captain Hook.",
        tags: ["Sport", "First 12a", "NRG"],
        link: "https://www.mountainproject.com/route/107147169/control",
        linkLabel: "View route",
        projectPick: true
    },
    {
        name: "The Vaporizer",
        grade: "5.12a",
        gradeRank: 25,
        location: "Rumney, NH",
        area: "Rumney",
        relevance: "First 12a Project",
        relevanceRank: 5,
        note: "A slightly more serious 12a option if he wants something more sustained after trying the cleaner intro picks.",
        tags: ["Sport", "First 12a", "Sustained"],
        link: "https://www.mountainproject.com/route/106732130/the-vaporizer",
        linkLabel: "View route",
        projectPick: true
    }
];
