const {test,expect}=require('@playwright/test');
const fs=require('node:fs');
test.use({viewport:{width:1440,height:1100},reducedMotion:'reduce'});
const snapshot=page=>page.evaluate(()=>window.marbleLab.snapshot());
const state=page=>page.evaluate(()=>window.marbleLab.state());
const advance=(page,ms)=>page.evaluate(ms=>window.advanceTime(ms),ms);
async function open(page){await page.goto('/marble-lab/');await expect(page.locator('body')).toHaveAttribute('data-demo-state','ready');}
async function range(page,id,value){await page.locator('#'+id).evaluate((el,v)=>{el.value=String(v);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));},value);}
async function clickAt(page,x,y){const p=await page.evaluate(({x,y})=>window.marbleLab.pointScreen(x,y),{x,y});await page.mouse.click(p.x,p.y);}
async function file(page,s){await page.locator('#machine-file').setInputFiles({name:'machine.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(s))});}
async function template(page,value){await page.locator('#new-machine').click();await page.locator('#machine-template').selectOption(value);await page.locator('#create-machine').click();}
test('starter is silent, catches three marbles, rings bells, pauses and resets',async({page})=>{
    const errors=[];page.on('pageerror',e=>errors.push(String(e)));await open(page);expect((await state(page)).audio.state).toBe('locked');expect((await state(page)).running).toBe(false);await page.locator('#run').click();await advance(page,1200);expect((await state(page)).marbles.length).toBeGreaterThan(0);await page.locator('#run').click();const paused=(await state(page)).time;await advance(page,1000);expect((await state(page)).time).toBe(paused);await page.locator('#run').click();await advance(page,14000);expect(await state(page)).toMatchObject({finished:true,caught:3,lost:0,bells:3});await expect(page.locator('#caught-count')).toHaveText('3');await page.screenshot({path:test.info().outputPath('starter-finish.png'),fullPage:true});await page.locator('#reset').click();expect(await state(page)).toMatchObject({started:false,caught:0,launched:0,time:0});expect(errors).toEqual([]);
});
test('keyboard placement, rotation, size, duplication, removal and history work',async({page})=>{
    await open(page);await page.locator('#lab-canvas').focus();await page.keyboard.press('a');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');expect((await snapshot(page)).pieces).toHaveLength(16);const p=(await snapshot(page)).pieces.at(-1);expect(p).toMatchObject({type:'ramp',x:550,y:395});await range(page,'angle',35);await range(page,'length',400);expect((await snapshot(page)).pieces.at(-1).angle).toBeCloseTo(35*Math.PI/180);expect((await snapshot(page)).pieces.at(-1).length).toBe(400);await page.locator('#duplicate').click();expect((await snapshot(page)).pieces).toHaveLength(17);await page.locator('#remove-part').click();expect((await snapshot(page)).pieces).toHaveLength(16);await page.locator('#undo').click();expect((await snapshot(page)).pieces).toHaveLength(17);await page.locator('#redo').click();expect((await snapshot(page)).pieces).toHaveLength(16);await page.locator('#lab-canvas').focus();await page.keyboard.press('Control+z');await page.keyboard.press('Delete');expect((await snapshot(page)).pieces).toHaveLength(16);await page.screenshot({path:test.info().outputPath('editor-desktop.png'),fullPage:true});
});
test('pointer drag is one undo stroke; release can move; snap and source count persist',async({page})=>{
    await open(page);const start=await page.evaluate(()=>window.marbleLab.pointScreen(330,180)),end=await page.evaluate(()=>window.marbleLab.pointScreen(380,230));await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(end.x,end.y,{steps:10});await page.mouse.up();expect((await snapshot(page)).pieces[0].x).toBeCloseTo(380,3);expect((await snapshot(page)).pieces[0].y).toBeCloseTo(230,3);expect((await state(page)).undo).toBe(1);await page.locator('#undo').click();expect((await snapshot(page)).pieces[0]).toMatchObject({x:330,y:180});await page.locator('#grid').click();await page.locator('[data-tool="bumper"]').click();await clickAt(page,480,505);expect((await snapshot(page)).pieces.at(-1)).toMatchObject({x:475,y:500});await range(page,'power',150);expect((await snapshot(page)).pieces.at(-1).power).toBe(1.5);
    await page.getByRole('button',{name:'Select marble release',exact:true}).click();await page.locator('#marble-count').fill('5');await page.locator('#marble-count').press('Tab');expect((await snapshot(page)).source.count).toBe(5);await page.waitForTimeout(450);await page.reload();expect((await snapshot(page)).source.count).toBe(5);expect((await snapshot(page)).pieces).toHaveLength(16);
});
test('portal editor pairs two parts, rejects overcrowded pairs and duplicates validly',async({page})=>{
    await open(page);await template(page,'blank');await page.locator('[data-tool="portal"]').click();await clickAt(page,250,280);await clickAt(page,650,400);let s=await snapshot(page);expect(s.pieces.filter(p=>p.type==='portal').map(p=>p.link)).toEqual([1,1]);await expect(page.locator('#portal-status')).toContainText('Paired');await clickAt(page,850,300);expect((await snapshot(page)).pieces.at(-1).link).toBe(2);await page.locator('#portal-link').fill('1');await page.locator('#portal-link').press('Tab');await expect(page.locator('#notice')).toContainText('pair number');expect((await snapshot(page)).pieces.at(-1).link).toBe(2);await page.locator('#duplicate').click();s=await snapshot(page);expect(s.pieces.filter(p=>p.type==='portal').map(p=>p.link)).toEqual([1,1,2,2]);expect(await page.evaluate(async()=>Boolean((await import('/marble-lab/model.js')).validateMachine(window.marbleLab.snapshot())))).toBe(true);
});
test('challenge locks, palette restrictions, budgets and failed outcomes are enforced',async({page})=>{
    await open(page);page.on('dialog',d=>d.accept());await page.locator('#mode').selectOption('five');await expect(page.locator('#release')).toBeDisabled();await expect(page.locator('[data-tool="portal"]')).toBeDisabled();await expect(page.locator('#remove-part')).toBeDisabled();await page.getByRole('button',{name:'Select marble release',exact:true}).click();await expect(page.locator('#marble-count')).toBeDisabled();await page.locator('[data-tool="ramp"]').click();for(let i=0;i<5;i++)await clickAt(page,260+i*150,220+i*70);await clickAt(page,1000,580);await expect(page.locator('#notice')).toContainText('5 added pieces');expect((await snapshot(page)).pieces.filter(p=>!p.locked)).toHaveLength(5);
    await template(page,'five');await page.locator('#run').click();await advance(page,15000);expect(await state(page)).toMatchObject({finished:true,won:false,caught:0,lost:3});await expect(page.locator('#challenge-medals')).toHaveText('0 / 3 solved');
});
test('all three challenges have valid solvable machines; wins survive reload',async({page})=>{
    await open(page);page.on('dialog',d=>d.accept());for(const key of ['five','bell','portal']){
        const s=await page.evaluate(async key=>{const {createMachine,part}=await import('/marble-lab/model.js');const s=createMachine(key);if(key==='five')s.pieces.push(part(2,'ramp',440,280,{length:620,angle:.45}),part(3,'funnel',800,540,{length:300}));if(key==='bell')s.pieces.push(part(3,'ramp',385,210,{length:430,angle:.4}),part(4,'funnel',620,310,{length:180}),part(5,'funnel',620,500,{length:250}));if(key==='portal')s.pieces.push(part(3,'portal',170,400,{link:1}),part(4,'portal',850,430,{link:1}));return s;},key);await file(page,s);await expect(page.locator('#mode')).toHaveValue(key);await page.locator('#run').click();await advance(page,15000);expect(await state(page)).toMatchObject({finished:true,won:true,caught:3,lost:0});await page.screenshot({path:test.info().outputPath(`challenge-${key}.png`),fullPage:true});
    }await expect(page.locator('#challenge-medals')).toHaveText('3 / 3 solved');await page.reload();await expect(page.locator('#challenge-medals')).toHaveText('3 / 3 solved');
});
test('Special delivery can be built and won using visible editor controls',async({page})=>{
    await open(page);await template(page,'portal');await page.locator('[data-tool="portal"]').click();await clickAt(page,170,400);await clickAt(page,850,430);expect((await snapshot(page)).pieces).toHaveLength(4);await page.locator('#run').click();await advance(page,10000);expect(await state(page)).toMatchObject({won:true,caught:3,portals:3});await expect(page.locator('#run-status')).toHaveText('Challenge solved!');
});
test('physics mechanisms really affect motion; fast contacts and determinism stay stable',async({page})=>{
    await open(page);const result=await page.evaluate(async()=>{
        const {Simulation}=await import('/marble-lab/physics.js'),{createMachine,part}=await import('/marble-lab/model.js');
        function fixture(type,extras={}){const m=createMachine('blank');m.source={x:400,y:120,count:1};m.pieces=[part(1,type,400,220,extras)];const s=new Simulation(m);s.running=true;s.started=true;s.nextLaunch=Infinity;const b=s.spawn();return {s,b,m};}
        let {s,b}=fixture('bumper');s.step(.65);const bumper=b.vy;
        ({s,b}=fixture('belt',{length:300}));s.step(1);const belt=b.vx;
        ({s,b}=fixture('magnet'));b.x=300;s.step(.4);const magnet=b.vx;
        ({s,b}=fixture('portal',{link:1}));s.machine.pieces.push(part(2,'portal',800,300,{link:1,angle:Math.PI/2}));s.step(.8);const portal={hits:b.portalHits,x:b.x,vx:b.vx};
        ({s,b}=fixture('switch'));s.machine.pieces.push(part(2,'gate',400,400));s.step(.65);const gate=s.gatesOpen;
        ({s,b}=fixture('domino',{x:410,y:250}));s.machine.pieces[0].x=410;s.machine.pieces.push(part(2,'domino',450,250),part(3,'domino',490,250));s.reset(s.machine);s.running=true;s.started=true;s.nextLaunch=Infinity;b=s.spawn();b.x=375;b.y=210;b.vx=400;b.vy=0;s.step(1);const dominos=s.state().dominos;
        ({s,b}=fixture('ramp',{length:400,angle:0}));b.y=150;b.vy=900;s.step(.15);const rail=b.y;
        const a=new Simulation(createMachine()),c=new Simulation(createMachine());a.start();c.start();for(let i=0;i<1200;i++)a.step(1/120);for(let i=0;i<600;i++)c.step(1/60);return {bumper,belt,magnet,portal,gate,dominos,rail,equal:JSON.stringify(a.state())===JSON.stringify(c.state())};
    });expect(result.bumper).toBeLessThan(0);expect(result.belt).toBeGreaterThan(50);expect(result.magnet).toBeGreaterThan(0);expect(result.portal.hits).toBe(1);expect(result.portal.x).toBeGreaterThan(600);expect(result.portal.vx).toBeLessThan(-50);expect(result.gate).toBe(true);expect(result.dominos.filter(d=>Math.abs(d.angle)>.3)).toHaveLength(3);expect(result.rail).toBeLessThan(220);expect(result.equal).toBe(true);
});
test('camera, following, slow motion, trails, fit and fullscreen use real controls',async({page})=>{
    await open(page);await page.locator('#speed').selectOption('0.25');await page.locator('#run').click();await advance(page,1000);expect((await state(page)).time).toBeLessThan(.5);await page.locator('#follow').click();await expect.poll(async()=>(await state(page)).zoom).toBe(2.1);await advance(page,6000);await page.locator('#next-marble').click();expect((await state(page)).followId).toBe(2);await page.screenshot({path:test.info().outputPath('follow-marble.png'),fullPage:true});await page.locator('#fit').click();expect(await state(page)).toMatchObject({follow:false,zoom:1});await page.locator('#trails').click();await expect(page.locator('#trails')).toHaveAttribute('aria-pressed','false');await page.locator('#zoom-in').click();expect((await state(page)).zoom).toBeGreaterThan(1);await page.locator('#zoom-out').click();expect((await state(page)).zoom).toBeCloseTo(1);await page.locator('#lab-canvas').focus();await page.keyboard.press('f');await expect.poll(()=>page.evaluate(()=>document.fullscreenElement?.id)).toBe('lab-stage');await page.keyboard.press('f');await expect.poll(()=>page.evaluate(()=>Boolean(document.fullscreenElement))).toBe(false);
});
test('save, JSON and PNG exports roundtrip; shelf survives reload and can remove entries',async({page})=>{
    await open(page);page.on('dialog',d=>d.accept());await page.locator('#machine-name').fill('Odd little machine');await page.locator('#save-machine').click();await expect(page.locator('#saved-machines')).toContainText('Odd little machine');await page.reload();await expect(page.locator('#machine-name')).toHaveValue('Odd little machine');const event=page.waitForEvent('download');await page.locator('#export-machine').click();const bytes=fs.readFileSync(await (await event).path()),s=JSON.parse(bytes);expect(s.pieces).toHaveLength(15);s.name='Imported contraption';await file(page,s);await expect(page.locator('#machine-name')).toHaveValue('Imported contraption');const picture=page.waitForEvent('download');await page.locator('#postcard').click();const png=fs.readFileSync(await (await picture).path());expect(png.subarray(0,8).toString('hex')).toBe('89504e470d0a1a0a');expect(png.length).toBeGreaterThan(10000);await page.getByRole('button',{name:'Open Odd little machine',exact:true}).click();await expect(page.locator('#machine-name')).toHaveValue('Odd little machine');await page.getByRole('button',{name:'Remove Odd little machine',exact:true}).click();await expect(page.locator('#saved-machines')).toContainText('No machines saved');
});
test('share links isolate drafts, never autorun, support same-page navigation and keep a copy',async({page,browser})=>{
    await open(page);await page.locator('#machine-name').fill('The shared machine');await page.locator('#share-machine').click();const link=await page.locator('#share-url').inputValue(),src=await snapshot(page);const context=await browser.newContext(),other=await context.newPage();await open(other);await other.locator('#machine-name').fill('Recipient draft');await other.locator('#machine-name').press('Tab');await other.waitForTimeout(450);await other.goto(link);await expect(other.locator('#shared-banner')).toBeVisible();expect(await snapshot(other)).toEqual(src);expect(await state(other)).toMatchObject({running:false,started:false,shared:true});await range(other,'length',450);await other.waitForTimeout(450);expect(await other.evaluate(()=>JSON.parse(localStorage.getItem('ethan-marble-lab-draft-v1')).name)).toBe('Recipient draft');await other.goto('/marble-lab/');await expect(other.locator('#machine-name')).toHaveValue('Recipient draft');await other.goto(link);await other.locator('#keep-machine').click();await expect(other.locator('#shared-banner')).toBeHidden();await other.waitForTimeout(450);await other.reload();await expect(other.locator('#machine-name')).toHaveValue('The shared machine');await other.evaluate(link=>location.hash=new URL(link).hash,link);await expect(other.locator('#shared-banner')).toBeVisible();await context.close();
});
test('invalid files, modified challenge locks, oversized layouts and malformed links preserve the draft',async({page})=>{
    await open(page);page.on('dialog',d=>d.accept());const original=await snapshot(page);for(const raw of [{v:1,pieces:[{}]}, {...original,source:{x:NaN,y:30,count:3}}, {...original,pieces:Array(61).fill(original.pieces[0])}]){await file(page,raw);await expect(page.locator('#notice')).toContainText('not a valid');expect(await snapshot(page)).toEqual(original);}const bad=await page.evaluate(async()=>{const m=(await import('/marble-lab/model.js')).createMachine('five');m.pieces[0].x=200;return m;});await file(page,bad);expect(await snapshot(page)).toEqual(original);await page.goto('/marble-lab/#machine=bad');await expect(page.locator('#notice')).toContainText('invalid');expect((await snapshot(page)).pieces).toHaveLength(15);
});
test('audio opt-in rings actual oscillators, disabling sound and hiding page stop them',async({page})=>{
    await open(page);page.on('dialog',d=>d.accept());const s=await page.evaluate(async()=>{const {createMachine,part}=await import('/marble-lab/model.js'),s=createMachine('blank');s.source={x:400,y:80,count:3};s.pieces=[part(1,'bell',400,170),part(2,'cup',400,620)];return s;});await file(page,s);await page.locator('#sound').click();expect((await state(page)).audio.enabled).toBe(true);await page.locator('#run').click();await expect.poll(async()=>(await state(page)).audio.strikes).toBeGreaterThan(0);await page.locator('#sound').click();expect((await state(page)).audio.enabled).toBe(false);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});expect((await state(page)).running).toBe(false);
});
test('blocked storage/audio and corrupted saved data remain honest and usable',async({page})=>{
    await page.addInitScript(()=>{localStorage.setItem('ethan-marble-lab-draft-v1','broken');localStorage.setItem('ethan-marble-lab-shelf-v1','{"oops":true}');window.AudioContext=undefined;window.webkitAudioContext=undefined;Storage.prototype.setItem=function(){throw new DOMException('Blocked','SecurityError');};});await open(page);expect((await snapshot(page)).pieces).toHaveLength(15);await page.locator('#sound').click();await expect(page.locator('#notice')).toContainText('Audio is unavailable');await page.locator('#save-machine').click();await expect(page.locator('#notice')).toContainText('Storage is unavailable');await page.locator('#run').click();await advance(page,15000);expect((await state(page)).caught).toBe(3);
});
test('native dialogs contain focus and restore their trigger',async({page})=>{
    await open(page);await page.locator('#share-machine').click();for(let i=0;i<8;i++){await page.keyboard.press('Tab');expect(await page.evaluate(()=>Boolean(document.activeElement.closest('#share-dialog')))).toBe(true);}await page.keyboard.press('Escape');await expect(page.locator('#share-machine')).toBeFocused();await page.locator('#new-machine').click();await page.keyboard.press('Escape');await expect(page.locator('#new-machine')).toBeFocused();
});
test('extra releases are additive and finish; rotating funnels and cups changes their physical geometry',async({page})=>{
    await open(page);await page.locator('#run').click();await page.locator('#release').click();await advance(page,16000);expect(await state(page)).toMatchObject({launched:4,finished:true});await page.locator('#reset').click();await page.locator('#release').click();await advance(page,16000);expect(await state(page)).toMatchObject({launched:1,finished:true});
    const result=await page.evaluate(async()=>{const {segments,part}=await import('/marble-lab/model.js'),{Simulation}=await import('/marble-lab/physics.js');const ramp=part(1,'funnel',400,300,{angle:Math.PI/2,length:100}),cup=part(2,'cup',600,300,{angle:-Math.PI/2,length:100});const m={source:{x:500,y:300,count:1},pieces:[cup],challenge:null},s=new Simulation(m);s.started=s.running=true;const b=s.spawn();b.x=540;b.vx=300;b.vy=0;s.step(.15);return {rails:segments(ramp),caught:s.caught};});expect(result.rails[0][0]).toBeCloseTo(424);expect(result.rails[0][1]).toBeCloseTo(250);expect(result.caught).toBe(1);
});
test('catalog, homepage, project discovery, favorite and Continue links work with loaded artwork',async({page})=>{
    await page.goto('/');await expect(page.getByRole('link',{name:'Build a Marble Machine'})).toHaveAttribute('href','marble-lab/');await page.goto('/projects/');await page.locator('[data-project-filter="play"]').click();const card=page.locator('.archive-card').filter({has:page.getByRole('heading',{name:'Marble Lab',exact:true})});await expect(card).toBeVisible();await card.scrollIntoViewIfNeeded();await expect.poll(()=>card.locator('img').evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);await card.screenshot({path:test.info().outputPath('project-card.png')});await card.getByRole('link',{name:'Open Marble Lab'}).click();await expect(page.locator('#lab-canvas')).toBeVisible();await page.goto('/games/');const game=page.locator('.game-marble');await game.getByRole('button',{name:'Add Marble Lab to favorites'}).click();await expect(game).toHaveClass(/is-favorite/);await expect(page.locator('#games-activity')).toContainText('Continue Marble Lab');await game.screenshot({path:test.info().outputPath('game-card.png')});await page.reload();await expect(game).toHaveClass(/is-favorite/);await expect(page.locator('.game-sound')).toBeVisible();await expect(page.locator('.game-worlds')).toBeVisible();
});
for(const width of [320,390,768])test(`touch controls and layout remain usable at ${width}px`,async({browser})=>{
    const context=await browser.newContext({viewport:{width,height:950},hasTouch:true,isMobile:width<500,reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));await open(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+1);await page.locator('[data-tool="bumper"]').tap();await page.locator('#lab-canvas').scrollIntoViewIfNeeded();const pt=await page.evaluate(()=>window.marbleLab.pointScreen(420,500));await page.touchscreen.tap(pt.x,pt.y);expect((await snapshot(page)).pieces).toHaveLength(16);await page.locator('#undo').tap();await page.locator('#run').tap();await advance(page,10000);expect((await state(page)).caught).toBe(3);await page.screenshot({path:test.info().outputPath(`touch-${width}.png`),fullPage:true});expect(errors).toEqual([]);await context.close();
});
