const {test,expect}=require('@playwright/test');
const fs=require('node:fs');
test.use({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const snapshot=page=>page.evaluate(()=>window.soundGarden.snapshot());
const state=page=>page.evaluate(()=>JSON.parse(window.render_game_to_text()));
async function open(page){await page.goto('/sound-garden/');await expect(page.locator('body')).toHaveAttribute('data-demo-state','ready');}
async function range(page,id,value){await page.locator('#'+id).evaluate((el,v)=>{el.value=String(v);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));},value);}
test('garden starts silent and Web Audio schedules real notes only after Play',async({page})=>{
    const errors=[];page.on('pageerror',e=>errors.push(String(e)));await open(page);expect((await state(page)).playing).toBe(false);expect((await state(page)).audio.state).toBe('locked');expect((await state(page)).audio.scheduled).toBe(0);
    await page.locator('#play').click();await expect.poll(async()=> (await state(page)).audio.scheduled).toBeGreaterThan(5);expect((await state(page)).audio.state).toBe('running');await expect(page.locator('#audio-status')).toHaveText('Your garden is playing');
    await page.locator('#mute').click();expect((await state(page)).muted).toBe(true);await expect(page.locator('#audio-status')).toContainText('monitor silent');await page.locator('#mute').click();await range(page,'volume',25);expect((await state(page)).volume).toBe(.25);
    await page.locator('#play').click();const count=(await state(page)).audio.scheduled;await page.waitForTimeout(200);expect((await state(page)).audio.scheduled).toBe(count);expect((await state(page)).audio.active).toBe(0);expect(errors).toEqual([]);
});
test('planting, individual patterns/mutes, removal and undo/redo use visible controls',async({page})=>{
    await open(page);await page.locator('#garden-canvas').focus();await page.keyboard.press('3');await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');let s=await snapshot(page);expect(s.plants).toHaveLength(7);const p=s.plants.at(-1);expect(p.type).toBe('bass');expect(p.x).toBe(6);expect(p.z).toBe(3);
    await page.locator('#pattern-preset').selectOption('eighths');expect((await snapshot(page)).plants.at(-1).pattern.filter(Boolean)).toHaveLength(8);
    await page.getByRole('button',{name:'Rhythm step 2',exact:true}).click();expect((await snapshot(page)).plants.at(-1).pattern[1]).toBe(true);await range(page,'object-gain',35);expect((await snapshot(page)).plants.at(-1).gain).toBe(.35);
    await page.locator('#object-mute').click();expect((await snapshot(page)).plants.at(-1).muted).toBe(true);await page.locator('#object-mute').click();expect((await snapshot(page)).plants.at(-1).muted).toBe(false);
    await page.locator('#remove-object').click();expect((await snapshot(page)).plants).toHaveLength(6);await page.locator('#undo').click();expect((await snapshot(page)).plants).toHaveLength(7);await page.locator('#redo').click();expect((await snapshot(page)).plants).toHaveLength(6);
    await page.locator('#garden-canvas').focus();await page.keyboard.press('Control+z');expect((await snapshot(page)).plants).toHaveLength(7);await page.keyboard.press('Delete');expect((await snapshot(page)).plants).toHaveLength(6);await page.screenshot({path:test.info().outputPath('editor-desktop.png'),fullPage:true});
});
test('dragging changes pitch/phase, respects occupied spaces, and makes one undo stroke',async({page})=>{
    await open(page);const point=await page.evaluate(()=>window.soundGarden.cellScreen(2,1)),target=await page.evaluate(()=>window.soundGarden.cellScreen(3,2));
    await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(target.x,target.y,{steps:8});await page.mouse.up();expect((await snapshot(page)).plants[0]).toMatchObject({x:3,z:2});expect((await state(page)).plants[0].note).toBe('C5');expect((await state(page)).plants[0].offset).toBe(3);expect((await state(page)).undo).toBe(1);
    const occupied=await page.evaluate(()=>window.soundGarden.cellScreen(7,2));await page.mouse.move(target.x,target.y);await page.mouse.down();await page.mouse.move(occupied.x,occupied.y);await page.mouse.up();expect((await snapshot(page)).plants[0]).toMatchObject({x:3,z:2});
    await page.locator('#undo').click();expect((await snapshot(page)).plants[0]).toMatchObject({x:2,z:1});
});
test('tempo/key/mood/swing and the deterministic transport affect the musical model',async({page})=>{
    await open(page);await range(page,'tempo',120);await range(page,'swing',25);await page.locator('#garden-key').selectOption('D');await page.locator('#garden-scale').selectOption('minor');expect(await snapshot(page)).toMatchObject({tempo:120,swing:.25,key:'D',scale:'minor'});expect((await state(page)).plants[0].note).toBe('F5');
    await page.locator('#play').click();await page.evaluate(()=>window.advanceTime(200));expect((await state(page)).step).toBe(1);await page.locator('#restart').click();await page.evaluate(()=>window.advanceTime(50));expect((await state(page)).step).toBe(0);
    await page.locator('#play').click();const paused=(await state(page)).step;await page.evaluate(()=>window.advanceTime(10000));expect((await state(page)).step).toBe(paused);await page.locator('#garden-canvas').focus();await page.keyboard.press('Space');expect((await state(page)).playing).toBe(true);await page.keyboard.press('Space');expect((await state(page)).playing).toBe(false);
});
test('save/reload and same-page share links isolate the recipient draft and never autoplay',async({page,browser})=>{
    await open(page);await page.locator('#garden-name').fill('Tiny orchestra 🌱');await page.locator('#save-garden').click();await expect(page.locator('#saved-gardens')).toContainText('Tiny orchestra 🌱');await page.reload();await expect(page.locator('#garden-name')).toHaveValue('Tiny orchestra 🌱');
    await page.locator('#share-garden').click();const link=await page.locator('#share-url').inputValue(),source=await snapshot(page);const context=await browser.newContext({reducedMotion:'reduce'}),other=await context.newPage();await open(other);await other.locator('#garden-name').fill('My draft');await other.locator('#save-garden').click();await other.goto(link);await expect(other.locator('#shared-banner')).toBeVisible();expect(await snapshot(other)).toEqual(source);expect((await state(other)).playing).toBe(false);expect((await state(other)).audio.state).toBe('locked');
    await range(other,'tempo',65);await other.waitForTimeout(550);expect(await other.evaluate(()=>JSON.parse(localStorage.getItem('ethan-sound-garden-draft-v1')).name)).toBe('My draft');await other.goto('/sound-garden/');await expect(other.locator('#garden-name')).toHaveValue('My draft');await other.goto(link);await other.locator('#keep-garden').click();await expect(other.locator('#shared-banner')).toBeHidden();await other.reload();await expect(other.locator('#garden-name')).toHaveValue('Tiny orchestra 🌱');await context.close();
});
test('WAV export produces an audible unclipped recording; every instrument synthesizes audio',async({page})=>{
    await open(page);const event=page.waitForEvent('download');await page.locator('#download-loop').click();const file=await event,bytes=fs.readFileSync(await file.path());expect(bytes.toString('ascii',0,4)).toBe('RIFF');expect(bytes.toString('ascii',8,12)).toBe('WAVE');expect(bytes.readUInt32LE(24)).toBe(44100);let peak=0,sum=0;for(let i=44;i<bytes.length;i+=2){const v=bytes.readInt16LE(i)/32768;peak=Math.max(peak,Math.abs(v));sum+=v*v;}expect(Math.sqrt(sum/((bytes.length-44)/2))).toBeGreaterThan(.002);expect(peak).toBeGreaterThan(.01);expect(peak).toBeLessThan(.95);
    const levels=await page.evaluate(async()=>{const {renderLoop}=await import('/sound-garden/audio.js'),{createGarden,plant}=await import('/sound-garden/model.js');const result={};for(const type of ['bell','reed','bass','drum','shaker']){const s=createGarden('blank');s.plants=[plant(1,type,0,4)];const bytes=await (await renderLoop(s)).arrayBuffer(),view=new DataView(bytes);let sum=0;for(let i=44;i<view.byteLength;i+=2)sum+=Math.abs(view.getInt16(i,true));result[type]=sum;}return result;});for(const value of Object.values(levels))expect(value).toBeGreaterThan(10000);
});
test('file roundtrip, invalid input, capacity and local shelf management',async({page})=>{
    await open(page);page.on('dialog',d=>d.accept());const event=page.waitForEvent('download');await page.locator('#export-garden').click();const file=await event,raw=JSON.parse(fs.readFileSync(await file.path(),'utf8'));raw.name='Imported garden';raw.tempo=101;await page.locator('#garden-file').setInputFiles({name:'garden.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(raw))});await expect(page.locator('#garden-name')).toHaveValue('Imported garden');expect((await snapshot(page)).tempo).toBe(101);
    await page.locator('#garden-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"v":1,"plants":[{}]}')});await expect(page.locator('#notice')).toContainText('not a valid');await expect(page.locator('#garden-name')).toHaveValue('Imported garden');
    await page.locator('#save-garden').click();await page.locator('#new-garden').click();await page.locator('#garden-template').selectOption('blank');await page.locator('#create-garden').click();expect((await snapshot(page)).plants).toHaveLength(0);await page.locator('#download-loop').click();await expect(page.locator('#notice')).toContainText('audible pattern');await page.getByRole('button',{name:'Open Imported garden',exact:true}).click();expect((await snapshot(page)).plants).toHaveLength(6);await page.getByRole('button',{name:'Remove Imported garden',exact:true}).click();await expect(page.locator('#saved-gardens')).toContainText('No compositions saved');
    const full=await page.evaluate(async()=>{const m=await import('/sound-garden/model.js'),s=m.createGarden('blank');for(let i=0;i<24;i++)s.plants.push(m.plant(i+1,'bell',i%12,Math.floor(i/12)));return JSON.stringify(s);});await page.locator('#garden-file').setInputFiles({name:'full.json',mimeType:'application/json',buffer:Buffer.from(full)});await page.locator('#garden-canvas').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await expect(page.locator('#notice')).toContainText('24 sounds');expect((await snapshot(page)).plants).toHaveLength(24);await page.goto('/sound-garden/#garden=bad');await expect(page.locator('#notice')).toContainText('invalid');expect((await snapshot(page)).plants).toHaveLength(24);
});
test('audio/storage denial remain honest, playable and exportable',async({page})=>{
    await page.addInitScript(()=>{window.AudioContext=undefined;window.webkitAudioContext=undefined;Storage.prototype.setItem=function(){throw new DOMException('Blocked','SecurityError');};});await open(page);await page.locator('#play').click();await expect(page.locator('#audio-status')).toContainText('audio unavailable');expect((await state(page)).playing).toBe(true);await page.locator('#play').click();await page.locator('#save-garden').click();await expect(page.locator('#notice')).toContainText('Storage is unavailable');await page.locator('#garden-canvas').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');expect((await snapshot(page)).plants).toHaveLength(7);
});
test('fullscreen and dialogs keep keyboard focus usable',async({page})=>{
    await open(page);await page.locator('#garden-canvas').focus();await page.keyboard.press('f');await expect.poll(()=>page.evaluate(()=>document.fullscreenElement?.id)).toBe('garden-stage');await page.keyboard.press('f');await expect.poll(()=>page.evaluate(()=>Boolean(document.fullscreenElement))).toBe(false);await page.locator('#share-garden').click();for(let i=0;i<7;i++){await page.keyboard.press('Tab');expect(await page.evaluate(()=>Boolean(document.activeElement.closest('#share-dialog')))).toBe(true);}await page.keyboard.press('Escape');await expect(page.locator('#share-garden')).toBeFocused();
});
test('catalogs/homepage/favorites/Continue integrate Sound Garden without replacing Pocket Worlds',async({page})=>{
    await page.goto('/');await expect(page.getByRole('link',{name:'Compose a Sound Garden'})).toHaveAttribute('href','sound-garden/');await expect(page.getByRole('link',{name:'Build a Pocket World'})).toBeVisible();
    await page.goto('/projects/');const card=page.locator('.archive-card').filter({has:page.getByRole('heading',{name:'Sound Garden',exact:true})});await page.locator('[data-project-filter="play"]').click();await expect(card).toBeVisible();await card.scrollIntoViewIfNeeded();await expect.poll(()=>card.locator('img').evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);await card.screenshot({path:test.info().outputPath('project-card.png')});await card.getByRole('link',{name:'Open Sound Garden'}).click();await expect(page.locator('#garden-canvas')).toBeVisible();
    await page.goto('/games/');const game=page.locator('.game-sound');await game.getByRole('button',{name:'Add Sound Garden to favorites'}).click();await expect(game).toHaveClass(/is-favorite/);await expect(page.locator('#games-activity')).toContainText('Continue Sound Garden');await game.screenshot({path:test.info().outputPath('game-card.png')});await page.reload();await expect(game).toHaveClass(/is-favorite/);
});
for(const width of [320,390,768])test(`touch editor stays usable at ${width}px`,async({browser})=>{
    const context=await browser.newContext({viewport:{width,height:950},isMobile:width<500,hasTouch:true,reducedMotion:'reduce'}),page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));await open(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+1);await page.locator('[data-tool="reed"]').tap();await page.locator('#play').tap();await expect(page.locator('#play')).toHaveAttribute('aria-pressed','true');await page.locator('#play').tap();await page.getByRole('button',{name:'Rhythm step 2',exact:true}).tap();await page.screenshot({path:test.info().outputPath(`touch-${width}.png`),fullPage:true});expect(errors).toEqual([]);await context.close();
});
