import {COLS,ROWS,LIMIT,instruments,plant,createGarden,validateGarden,pitch,offset,sounding,stepSeconds,pattern,encodeGarden,decodeGarden,clamp} from './model.js';
import {GardenAudio,renderLoop} from './audio.js';
import {GardenRenderer} from './render.js';
const $=id=>document.getElementById(id),canvas=$('garden-canvas'),stage=$('garden-stage'),clone=v=>JSON.parse(JSON.stringify(v));
const draftKey='ethan-sound-garden-draft-v1',savesKey='ethan-sound-gardens-v1';
let scene=createGarden(),saves=[],shared=false,selected=1,tool='bell',cursor=null,history=[],future=[],drag=null,dirty=false,draftTimer=0,toastTimer=0;
let playing=false,starting=false,volume=.5,muted=false,visualStep=-1,nextStep=0,nextAt=0,queue=[],manual=false,manualClock=0,timer=0,time=.001,lastFrame=0;
const pulses=new Map(),audio=new GardenAudio(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function notice(s){$('notice').textContent=s;$('notice').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('notice').hidden=true,4300);}
try{const raw=localStorage.getItem(draftKey);if(raw)scene=validateGarden(JSON.parse(raw));}catch{notice('Could not restore the draft. You can import a saved garden file.');}
try{const raw=JSON.parse(localStorage.getItem(savesKey)||'[]');if(Array.isArray(raw))saves=raw.slice(0,6).flatMap(s=>{try{return[{id:String(s.id),scene:validateGarden(s.scene)}];}catch{return[];}});}catch{notice('Saved compositions could not be read. Your exported files are still usable.');}
if(location.hash.startsWith('#garden=')){try{scene=decodeGarden(location.hash.slice(8));shared=true;}catch{notice('That garden link is invalid. Your local draft is unchanged.');}}
selected=scene.plants[0]?.id||null;
let renderer;try{renderer=new GardenRenderer(canvas);}catch{document.body.dataset.demoState='error';$('audio-status').textContent='Canvas is unavailable. Try a browser with Canvas support.';throw new Error('Sound Garden needs Canvas2D');}
function saveDraft(){if(shared)return;try{localStorage.setItem(draftKey,JSON.stringify(scene));dirty=false;$('save-state').textContent='Draft saved locally';}catch{$('save-state').textContent='Storage unavailable';}}
function changed(){dirty=true;clearTimeout(draftTimer);if(!shared)draftTimer=setTimeout(saveDraft,450);updateUI();}
function checkpoint(before){history.push(before);if(history.length>50)history.shift();future=[];changed();}
function finishDrag(){if(drag?.changed){checkpoint(drag.before);resync();}drag=null;}
function mutate(fn){finishDrag();const before=clone(scene);fn();if(JSON.stringify(scene)!==JSON.stringify(before)){checkpoint(before);resync();}else updateUI();draw();}
function current(){return scene.plants.find(p=>p.id===selected)||null;}
function choose(id){selected=id;updateUI();draw();}
function clock(){return manual?manualClock:audio.ctx?.state==='running'?audio.now:performance.now()/1000;}
function schedule(now){if(!playing)return;let guard=0;while(nextAt<=now+(manual?0:.10)&&guard++<1024){const step=nextStep,ids=[];for(const p of scene.plants)if(sounding(p,step)){ids.push(p.id);if(!manual)audio.play(p,scene,nextAt);}queue.push({at:nextAt,step,ids});nextAt+=stepSeconds(scene,step);nextStep=(step+1)%16;}}
function consume(now){while(queue.length&&queue[0].at<=now){const event=queue.shift();visualStep=event.step;event.ids.forEach(id=>pulses.set(id,time));updateBeat();}}
function updateBeat(){[...$('beat-strip').children].forEach((el,i)=>el.classList.toggle('active',playing&&i===visualStep));const p=current();[...$('pattern-grid').children].forEach((el,i)=>el.classList.toggle('current',playing&&p&&i===(visualStep-offset(p)+16)%16));}
function resync(){if(!playing)return;audio.stop();queue=[];nextAt=clock()+.035;nextStep=(visualStep+1+16)%16;}
function stop(){playing=false;clearInterval(timer);timer=0;audio.stop();queue=[];updateUI();updateBeat();}
async function playPause(){if(playing){stop();return;}if(starting)return;starting=true;$('play').disabled=true;const unlocked=await audio.unlock();starting=false;$('play').disabled=false;if(document.hidden)return;
    playing=true;audio.volume(volume,muted);nextStep=0;visualStep=-1;queue=[];nextAt=clock()+.025;if(!unlocked)notice('Audio is unavailable. You can still arrange and watch the garden.');
    if(audio.ctx)audio.ctx.onstatechange=()=>{if(playing&&audio.ctx.state!=='running'){stop();notice('Audio was interrupted. Press Play to resume.');}};
    timer=setInterval(()=>{if(!manual)schedule(clock());},25);schedule(clock());updateUI();
}
function draw(){renderer.draw(scene,{selected,cursor,pulses,time,reduced});}
function frame(now){const dt=lastFrame?Math.min((now-lastFrame)/1000,.05):0;lastFrame=now;if(!manual)time+=dt;if(playing&&!manual){schedule(clock());consume(clock());}draw();requestAnimationFrame(frame);}
function updateUI(){
    if(document.activeElement!==$('garden-name'))$('garden-name').value=scene.name;$('shared-banner').hidden=!shared;
    document.querySelectorAll('[data-tool]').forEach(b=>{const active=b.dataset.tool===tool;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});
    $('play').textContent=playing?'Ⅱ Pause':'▶ Play garden';$('play').setAttribute('aria-pressed',String(playing));$('mute').textContent=muted?'Sound off':'Sound on';$('mute').setAttribute('aria-pressed',String(muted));
    $('audio-status').textContent=playing?(audio.ctx?.state==='running'?(muted||volume===0?'Playing · monitor silent':'Your garden is playing'):'Playing visually · audio unavailable'):'Press Play to hear your garden';
    $('undo').disabled=!history.length;$('redo').disabled=!future.length;$('tempo').value=scene.tempo;$('tempo-label').textContent=scene.tempo+' BPM';$('garden-key').value=scene.key;$('garden-scale').value=scene.scale;$('swing').value=Math.round(scene.swing*100);$('swing-label').textContent=Math.round(scene.swing*100)+'%';$('volume-label').textContent=Math.round(volume*100)+'%';
    const p=current();$('selected-controls').hidden=!p;$('selection-empty').hidden=Boolean(p);$('selected-name').textContent=p?instruments[p.type].name:'A little silence';$('selected-detail').textContent=p?instruments[p.type].voice+(p.type==='drum'||p.type==='shaker'?'':` · ${pitch(p,scene).name}`):'Choose a sound to edit';
    if(p){$('phase-label').textContent='Starts step '+(offset(p)+1);[...$('pattern-grid').children].forEach((b,i)=>b.setAttribute('aria-pressed',String(p.pattern[i])));$('object-gain').value=Math.round(p.gain*100);$('gain-label').textContent=Math.round(p.gain*100)+'%';$('object-mute').textContent=p.muted?'Unmute object':'Mute object';$('object-mute').setAttribute('aria-pressed',String(p.muted));}
    $('object-count').textContent=`${scene.plants.length} / ${LIMIT}`;const list=$('voice-list'),ids=new Set(scene.plants.map(p=>String(p.id)));[...list.children].forEach(b=>{if(!ids.has(b.dataset.id))b.remove();});
    for(const p of scene.plants){let b=list.querySelector(`[data-id="${p.id}"]`);if(!b){b=document.createElement('button');b.dataset.id=p.id;b.onclick=()=>choose(p.id);list.append(b);}const info=instruments[p.type];b.textContent=info.glyph;b.style.color=info.color;b.setAttribute('aria-label',`Select ${info.name} ${p.id}, ${p.type==='drum'||p.type==='shaker'?'percussion':pitch(p,scene).name}${p.muted?', muted':''}`);b.title=b.getAttribute('aria-label');b.setAttribute('aria-pressed',String(p.id===selected));b.classList.toggle('is-muted',p.muted);}
    updateBeat();
}
for(let i=0;i<16;i++){const beat=document.createElement('span');beat.setAttribute('aria-hidden','true');$('beat-strip').append(beat);const b=document.createElement('button');b.textContent=i+1;b.setAttribute('aria-label',`Rhythm step ${i+1}`);b.setAttribute('aria-pressed','false');b.onclick=()=>{if(current())mutate(()=>current().pattern[i]=!current().pattern[i]);};$('pattern-grid').append(b);}
document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>{finishDrag();tool=b.dataset.tool;updateUI();}));
function addAt(p){if(!p)return;const existing=scene.plants.find(o=>o.x===p.x&&o.z===p.z);if(existing){choose(existing.id);return;}if(tool==='select')return;if(scene.plants.length>=LIMIT){notice('This garden has room for 24 sounds. Remove one to plant another.');return;}let id=1;while(scene.plants.some(p=>p.id===id))id++;mutate(()=>{scene.plants.push(plant(id,tool,p.x,p.z));selected=id;});}
canvas.addEventListener('pointerdown',e=>{if(e.button!==0||drag)return;canvas.focus({preventScroll:true});const id=renderer.hit(e.clientX,e.clientY);if(id){choose(id);const p=current(),point=renderer.cellScreen(p.x,p.z);drag={id:e.pointerId,plant:id,before:clone(scene),changed:false,dx:e.clientX-point.x,dy:e.clientY-point.y};canvas.setPointerCapture(e.pointerId);}else{cursor=renderer.cell(e.clientX,e.clientY);addAt(cursor);}draw();});
canvas.addEventListener('pointermove',e=>{if(drag&&drag.id===e.pointerId){const cell=renderer.cell(e.clientX-drag.dx,e.clientY-drag.dy),p=scene.plants.find(o=>o.id===drag.plant);if(cell&&p&&!scene.plants.some(o=>o.id!==p.id&&o.x===cell.x&&o.z===cell.z)&&(p.x!==cell.x||p.z!==cell.z)){p.x=cell.x;p.z=cell.z;drag.changed=true;cursor=cell;updateUI();}}else cursor=renderer.cell(e.clientX,e.clientY);draw();});
canvas.addEventListener('pointerup',e=>{if(drag?.id===e.pointerId){finishDrag();if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);}draw();});canvas.addEventListener('pointercancel',finishDrag);canvas.addEventListener('lostpointercapture',finishDrag);canvas.addEventListener('pointerleave',()=>{if(!drag){cursor=null;draw();}});
function remove(){if(!current())return;mutate(()=>{scene.plants=scene.plants.filter(p=>p.id!==selected);pulses.delete(selected);selected=scene.plants[0]?.id||null;});}
function undo(){finishDrag();if(!history.length)return;future.push(clone(scene));scene=history.pop();selected=scene.plants[0]?.id||null;changed();resync();draw();}
function redo(){finishDrag();if(!future.length)return;history.push(clone(scene));scene=future.pop();selected=scene.plants[0]?.id||null;changed();resync();draw();}
$('undo').onclick=undo;$('redo').onclick=redo;$('remove-object').onclick=remove;$('object-mute').onclick=()=>{if(current())mutate(()=>current().muted=!current().muted);};
$('object-gain').addEventListener('change',e=>{if(current())mutate(()=>current().gain=Number(e.target.value)/100);});$('pattern-preset').addEventListener('change',e=>{if(e.target.value&&current())mutate(()=>current().pattern=pattern(e.target.value));e.target.value='';});
$('garden-name').addEventListener('change',e=>mutate(()=>scene.name=e.target.value.trim().slice(0,40)||'Untitled garden'));
$('tempo').addEventListener('change',e=>mutate(()=>scene.tempo=Number(e.target.value)));$('swing').addEventListener('change',e=>mutate(()=>scene.swing=Number(e.target.value)/100));$('garden-key').onchange=e=>mutate(()=>scene.key=e.target.value);$('garden-scale').onchange=e=>mutate(()=>scene.scale=e.target.value);
$('volume').addEventListener('input',e=>{volume=Number(e.target.value)/100;audio.volume(volume,muted);updateUI();});$('mute').onclick=()=>{muted=!muted;audio.volume(volume,muted);updateUI();};$('play').onclick=playPause;$('restart').onclick=()=>{audio.stop();queue=[];visualStep=-1;nextStep=0;nextAt=clock()+.025;pulses.clear();updateBeat();};
for(const [id,label,suffix] of [['tempo','tempo-label',' BPM'],['swing','swing-label','%'],['object-gain','gain-label','%']])$(id).addEventListener('input',e=>$(label).textContent=e.target.value+suffix);
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await stage.requestFullscreen();}catch{notice('Fullscreen is unavailable in this browser.');}}
$('fullscreen').onclick=fullscreen;document.addEventListener('fullscreenchange',draw);
canvas.addEventListener('keydown',e=>{
    if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return;}
    if(/^[1-6]$/.test(e.key)){tool=[...Object.keys(instruments),'select'][Number(e.key)-1];updateUI();e.preventDefault();return;}
    if(e.code==='Space'){e.preventDefault();playPause();return;}if(e.key.toLowerCase()==='f'){e.preventDefault();fullscreen();return;}
    if(e.key.startsWith('Arrow')){e.preventDefault();cursor=cursor||{x:5,z:3};cursor={x:clamp(cursor.x+(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0),0,COLS-1),z:clamp(cursor.z+(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0),0,ROWS-1)};draw();}
    if(e.key==='Enter'){e.preventDefault();cursor=cursor||{x:5,z:3};addAt(cursor);}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove();}
});
function clearHash(){try{window.history.replaceState(null,'',location.pathname+location.search);}catch{/* Restricted embeds may block history. */}}
function setScene(next,fromShared=false){finishDrag();if(dirty&&!shared)saveDraft();clearTimeout(draftTimer);stop();scene=validateGarden(clone(next));selected=scene.plants[0]?.id||null;cursor=null;history=[];future=[];pulses.clear();shared=fromShared;dirty=false;if(!shared){clearHash();saveDraft();}updateUI();draw();}
window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#garden=')){try{setScene(decodeGarden(location.hash.slice(8)),true);}catch{notice('That garden link is invalid. Nothing was changed.');}}else if(shared){try{setScene(JSON.parse(localStorage.getItem(draftKey)||'null')||createGarden());}catch{setScene(createGarden());}}});
function writeSaves(next){try{localStorage.setItem(savesKey,JSON.stringify(next));return true;}catch{notice('Storage is unavailable or full. Export a file to keep the composition.');return false;}}
function renderShelf(){const host=$('saved-gardens');host.replaceChildren();if(!saves.length){const p=document.createElement('p');p.className='empty-shelf';p.textContent='No compositions saved yet. Plant something worth keeping.';host.append(p);return;}for(const entry of saves){const card=document.createElement('article'),h=document.createElement('h3'),small=document.createElement('small'),actions=document.createElement('div'),open=document.createElement('button'),del=document.createElement('button');h.textContent=entry.scene.name;small.textContent=`${entry.scene.plants.length} sounds · ${entry.scene.tempo} BPM · ${entry.scene.key} ${entry.scene.scale}`;open.textContent='Open';open.setAttribute('aria-label',`Open ${entry.scene.name}`);del.textContent='Remove';del.setAttribute('aria-label',`Remove ${entry.scene.name}`);open.onclick=()=>{if(confirm('Open this composition? This replaces your current draft.'))setScene(entry.scene);};del.onclick=()=>{if(!confirm(`Remove ${entry.scene.name} from saved compositions?`))return;const next=saves.filter(s=>s.id!==entry.id);if(writeSaves(next)){saves=next;renderShelf();}};actions.append(open,del);card.append(h,small,actions);host.append(card);}}
function saveGarden(){finishDrag();if(saves.length>=6&&!confirm('Save this composition? Your oldest saved snapshot will be replaced.'))return;const next=[{id:crypto.randomUUID(),scene:clone(scene)},...saves].slice(0,6);if(writeSaves(next)){saves=next;if(shared){shared=false;clearHash();}saveDraft();renderShelf();updateUI();notice('Composition saved in this browser.');}}
$('save-garden').onclick=saveGarden;$('keep-garden').onclick=saveGarden;
$('share-garden').onclick=()=>{finishDrag();const url=new URL(location.href);url.hash='garden='+encodeGarden(scene);$('share-url').value=url.href;$('copy-status').textContent='';$('share-dialog').showModal();};$('copy-link').onclick=async()=>{try{await navigator.clipboard.writeText($('share-url').value);$('copy-status').textContent='Copied. Ready to play and remix.';}catch{$('share-url').focus();$('share-url').select();$('copy-status').textContent='Select and copy the link above.';}};
$('new-garden').onclick=()=>$('new-dialog').showModal();$('create-garden').onclick=()=>{setScene(createGarden($('garden-template').value));$('new-dialog').close();};
for(const id of ['share-dialog','new-dialog'])$(id).addEventListener('keydown',e=>{if(e.key!=='Tab')return;const els=[...$(id).querySelectorAll('button,input,select')].filter(el=>!el.disabled&&!el.hidden),first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const fileName=()=>scene.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'sound-garden';
$('export-garden').onclick=()=>{finishDrag();download(new Blob([JSON.stringify(scene,null,2)],{type:'application/json'}),fileName()+'.json');};$('import-garden').onclick=()=>$('garden-file').click();
$('garden-file').onchange=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>50000){notice('Choose a Sound Garden JSON export under 50 KB.');return;}try{const next=validateGarden(JSON.parse(await file.text()));if(confirm('Import this garden? This replaces your current draft.'))setScene(next);}catch{notice('That is not a valid Sound Garden file. Nothing was changed.');}};
$('download-loop').onclick=async()=>{if(volume===0||!scene.plants.some(p=>!p.muted&&p.gain>0&&p.pattern.some(Boolean))){notice('Give the garden an audible pattern and turn up Volume first.');return;}const button=$('download-loop'),snapshot=clone(scene),name=fileName();button.disabled=true;button.textContent='Rendering…';try{download(await renderLoop(snapshot,volume),name+'.wav');notice('Two bars and a soft ring-out, saved as WAV.');}catch(e){notice(e.message||'Could not export audio in this browser.');}finally{button.disabled=false;button.textContent='Download WAV';}};
document.addEventListener('visibilitychange',()=>{lastFrame=0;if(document.hidden){if(playing)stop();finishDrag();if(dirty)saveDraft();}});window.addEventListener('pagehide',()=>{stop();finishDrag();clearTimeout(draftTimer);if(dirty)saveDraft();});
window.advanceTime=ms=>{if(!manual){manual=true;manualClock=0;nextAt=0;nextStep=0;queue=[];audio.stop();}const seconds=clamp(Number(ms)||0,0,60000)/1000;for(let left=seconds;left>0;left-=.025){const dt=Math.min(.025,left);manualClock+=dt;time+=dt;schedule(manualClock);consume(manualClock);}draw();};
window.render_game_to_text=()=>JSON.stringify({mode:'sound-garden',name:scene.name,playing,muted,volume,tempo:scene.tempo,key:scene.key,scale:scene.scale,swing:scene.swing,step:visualStep,selected,tool,cursor,shared,coordinates:'12 × 8 garden spaces; x changes start step, z changes pentatonic pitch (z=0 highest)',plants:scene.plants.map(p=>({id:p.id,type:p.type,x:p.x,z:p.z,note:p.type==='shaker'||p.type==='drum'?'percussion':pitch(p,scene).name,offset:offset(p),pattern:p.pattern.map((v,i)=>v?i+1:null).filter(Boolean),gain:p.gain,muted:p.muted})),undo:history.length,redo:future.length,saved:saves.map(s=>s.scene.name),audio:audio.diagnostics()});
window.soundGarden={snapshot:()=>clone(scene),cellScreen:(x,z)=>renderer.cellScreen(x,z),audioDiagnostics:()=>audio.diagnostics()};
renderShelf();updateUI();draw();document.body.dataset.demoState='ready';requestAnimationFrame(frame);
