import {W,H,MAX_PARTS,parts,part,clamp,clone,challenges,createMachine,validateMachine,encodeMachine,decodeMachine} from './model.js';
import {Simulation} from './physics.js';
import {Renderer} from './render.js';
const $=id=>document.getElementById(id),DRAFT='ethan-marble-lab-draft-v1',SHELF='ethan-marble-lab-shelf-v1',MEDALS='ethan-marble-lab-medals-v1';
let noticeTimer,saveTimer,shared=false,storageOK=true,selected=1,tool='select',hover=null,cursor={x:550,y:370},snap=false,follow=false,speed=1,manual=false,drag=null,sliderBefore=null;
let undo=[],redo=[],machine,medals=[],saved=[];
function notice(text){$('notice').textContent=text;$('notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').hidden=true,4200);}
function read(key){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):null;}catch{return null;}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{storageOK=false;$('save-state').textContent='Storage unavailable';return false;}}
const draft=validateMachine(read(DRAFT));machine=draft||createMachine();
const rawShelf=read(SHELF);if(Array.isArray(rawShelf))saved=rawShelf.slice(0,6).map(validateMachine).filter(Boolean);
const rawMedals=read(MEDALS);if(Array.isArray(rawMedals))medals=rawMedals.filter(k=>Object.hasOwn(challenges,k));
const renderer=new Renderer($('lab-canvas'));
class Chimes{
    constructor(){this.context=null;this.enabled=false;this.last=-1;this.strikes=0;this.voices=new Set();}
    async toggle(){if(this.enabled){this.enabled=false;for(const o of this.voices){try{o.stop();}catch{}}return true;}try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return false;this.context ||= new AC();await this.context.resume();this.enabled=this.context.state==='running';return this.enabled;}catch{return false;}}
    hit(e){if(!this.enabled||!this.context||manual||document.hidden||!['bell','bumper','domino','catch'].includes(e.type))return;const ctx=this.context,t=ctx.currentTime;if(t-this.last<.04||this.voices.size>=8)return;this.last=t;this.strikes++;const o=ctx.createOscillator(),g=ctx.createGain();o.type=e.type==='bell'?'sine':'triangle';o.frequency.setValueAtTime(e.type==='bell'?523.25*Math.pow(2,(e.id%5)/12):e.type==='catch'?330:150,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.055,t+.004);g.gain.exponentialRampToValueAtTime(.0001,t+(e.type==='bell'?.8:.14));o.connect(g).connect(ctx.destination);this.voices.add(o);o.onended=()=>{this.voices.delete(o);o.disconnect();g.disconnect();};o.start(t);o.stop(t+1);}
    silence(){for(const o of this.voices){try{o.stop();}catch{}}}
}
const chimes=new Chimes();
const sim=new Simulation(machine,e=>{chimes.hit(e);if(e.type==='win'){if(!medals.includes(machine.challenge)){medals.push(machine.challenge);write(MEDALS,medals);}$('challenge-medals').textContent=`${new Set(medals).size} / 3 solved`;notice('Challenge solved. Beautiful chain reaction!');}});
function piece(){return machine.pieces.find(p=>p.id===selected);}
function resetRun(){sim.reset(machine);chimes.silence();manual=false;renderer.fit();follow=false;updateTransport();}
function remember(before){if(JSON.stringify(before)===JSON.stringify(machine))return;undo.push(before);if(undo.length>50)undo.shift();redo=[];resetRun();refresh();autosave();}
function edit(fn){const before=clone(machine);fn();remember(before);}
function autosave(){clearTimeout(saveTimer);if(shared){$('save-state').textContent='Shared snapshot';return;}$('save-state').textContent=storageOK?'Saving draft…':'Storage unavailable';saveTimer=setTimeout(()=>{if(write(DRAFT,machine))$('save-state').textContent='Draft saved locally';},350);}
function available(type){const c=challenges[machine.challenge];return !c||c.allowed.includes(type);}
function room(){const c=challenges[machine.challenge];if(machine.pieces.length>=MAX_PARTS){notice(`The table holds ${MAX_PARTS} parts.`);return false;}if(c&&machine.pieces.filter(p=>!p.locked).length>=c.budget){notice(`This challenge allows ${c.budget} added pieces.`);return false;}return true;}
function point(x,y){return {x:clamp(snap?Math.round(x/25)*25:x,25,W-25),y:clamp(snap?Math.round(y/25)*25:y,35,H-30)};}
function add(x,y){if(!parts[tool]||!available(tool)||!room())return;const pt=point(x,y);edit(()=>{const id=Math.max(0,...machine.pieces.map(p=>p.id))+1,p=part(id,tool,pt.x,pt.y);if(tool==='portal'){const portals=machine.pieces.filter(p=>p.type==='portal'),unpaired=portals.find(p=>p.link&&portals.filter(q=>q.link===p.link).length===1);p.link=unpaired?.link||Math.max(0,...portals.map(p=>p.link))+1;if(p.link>30)p.link=0;}machine.pieces.push(p);selected=id;});}
function remove(){const p=piece();if(!p||p.locked){if(p?.locked)notice('This challenge piece is fixed.');return;}edit(()=>{machine.pieces=machine.pieces.filter(q=>q.id!==p.id);selected=machine.pieces.find(q=>!q.locked)?.id||'source';});}
function duplicate(){const p=piece();if(!p||p.locked||!room())return;edit(()=>{const q={...p,id:Math.max(...machine.pieces.map(p=>p.id))+1,...point(p.x+35,p.y+35)};if(q.type==='portal'){const portals=machine.pieces.filter(v=>v.type==='portal'),unpaired=portals.find(v=>v.link&&portals.filter(w=>w.link===v.link).length===1);q.link=unpaired?.link||Array.from({length:30},(_,i)=>i+1).find(n=>!portals.some(v=>v.link===n))||0;}machine.pieces.push(q);selected=q.id;});}
function travelHistory(back){const from=back?undo:redo,to=back?redo:undo;if(!from.length)return;to.push(clone(machine));machine=from.pop();resetRun();if(selected!=='source'&&!piece())selected=machine.pieces[0]?.id||'source';refresh();autosave();}
function setTool(next){if(next!=='select'&&!available(next))return;tool=next;document.querySelectorAll('[data-tool]').forEach(b=>{const on=b.dataset.tool===tool;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});}
const labels={ramp:'Ramp',funnel:'Funnel',bumper:'Bumper',belt:'Conveyor',magnet:'Magnet',portal:'Portal',bell:'Bell',switch:'Switch',gate:'Gate',domino:'Domino',cup:'Cup'};
for(const [type,d] of [...Object.entries(parts),['select',{glyph:'↔',name:'Move'}]]){const b=document.createElement('button');b.dataset.tool=type;b.setAttribute('aria-label',type==='select'?'Select and move parts':`Place ${d.name}`);b.setAttribute('aria-pressed',String(type===tool));const icon=document.createElement('span');icon.textContent=d.glyph;icon.style.color=d.color||'#668578';icon.setAttribute('aria-hidden','true');b.append(icon,document.createTextNode(labels[type]||'Move'));b.addEventListener('click',()=>setTool(type));$('palette').append(b);}
function refresh(){
    if(document.activeElement!==$('machine-name'))$('machine-name').value=machine.name;
    $('mode').value=machine.challenge||'sandbox';const c=challenges[machine.challenge];$('challenge-description').textContent=c?c.description:'Build freely. The starter machine is ready to run.';$('challenge-medals').textContent=`${new Set(medals).size} / 3 solved`;
    $('part-count').textContent=c?`${machine.pieces.filter(p=>!p.locked).length} / ${c.budget} added`:`${machine.pieces.length} / ${MAX_PARTS}`;
    document.querySelectorAll('[data-tool]').forEach(b=>{b.disabled=!available(b.dataset.tool)&&b.dataset.tool!=='select';});if(!available(tool))setTool('select');
    const p=piece(),source=selected==='source',locked=source?Boolean(c):p?.locked;$('selected-name').textContent=source?'Marble release':p?parts[p.type].name:'Choose a part';$('selected-help').textContent=source?'Drag the release onto your first track.':p?parts[p.type].help:'Choose a part from the box, then click the table.';
    $('part-controls').hidden=!p;$('source-controls').hidden=!source;$('fixed-note').hidden=!locked;$('angle-control').hidden=!p||['bumper','magnet','bell','switch'].includes(p.type);$('size-control').hidden=p?.type==='bell';
    if(p){$('angle').value=Math.round(p.angle*180/Math.PI);$('angle-label').textContent=`${Math.round(p.angle*180/Math.PI)}°`;$('length').value=p.length;$('length-label').textContent=Math.round(p.length);$('power').value=p.power*100;$('power-label').textContent=p.power.toFixed(1);$('power-control').hidden=!['bumper','belt','magnet'].includes(p.type);$('portal-control').hidden=p.type!=='portal';$('portal-link').value=p.link||1;if(p.type==='portal'){$('portal-status').textContent=machine.pieces.filter(q=>q.type==='portal'&&q.link===p.link&&q.link).length===2?'Paired · ready to travel':'Unpaired · add another portal or match its number';}for(const id of ['angle','length','power','portal-link','duplicate','remove-part'])$(id).disabled=Boolean(locked);}
    $('marble-count').value=machine.source.count;$('marble-count').disabled=Boolean(c);$('undo').disabled=!undo.length;$('redo').disabled=!redo.length;
    $('piece-list').replaceChildren();const addChip=(id,text,name)=>{const b=document.createElement('button');b.textContent=text;b.setAttribute('aria-label',name);b.setAttribute('aria-pressed',String(selected===id));b.onclick=()=>{selected=id;setTool('select');refresh();};$('piece-list').append(b);};addChip('source','⇣','Select marble release');for(const p of machine.pieces)addChip(p.id,parts[p.type].glyph,`Select ${parts[p.type].name} ${p.id}`);
    setTool(tool);updateTransport();draw();
}
function updateTransport(){
    $('run').textContent=sim.running?'Ⅱ Pause':sim.finished?'▶ Run again':sim.started?'▶ Resume':'▶ Run machine';$('run').setAttribute('aria-pressed',String(sim.running));$('caught-count').textContent=sim.caught;$('lost-count').textContent=sim.lost;$('time-label').textContent=`${sim.time.toFixed(1)} s`;
    $('run-status').textContent=sim.won?'Challenge solved!':sim.finished?`${sim.caught} caught · ${sim.lost} missed${machine.challenge?' · reset and try again':''}`:sim.running?'Chain reaction in progress':sim.started?'Paused — take a closer look':'Ready to roll';$('release').disabled=Boolean(machine.challenge)||sim.launched>=40;$('next-marble').disabled=!sim.balls.some(b=>b.status==='active');$('follow').setAttribute('aria-pressed',String(follow));
}
function draw(){renderer.draw(machine,sim,{selected,hover,tool,cursor:$('lab-canvas')===document.activeElement?cursor:null,follow});}
function run(){manual=false;if(sim.running){sim.running=false;chimes.silence();}else sim.start();updateTransport();}
$('run').onclick=run;$('reset').onclick=()=>{resetRun();draw();};$('release').onclick=()=>{if(machine.challenge)return;if(sim.finished)sim.reset(machine);if(!sim.started){sim.started=true;sim.nextLaunch=Infinity;}sim.spawn();sim.running=true;manual=false;updateTransport();};
$('speed').onchange=()=>speed=Number($('speed').value);$('follow').onclick=()=>{follow=!follow;if(!follow)renderer.fit();updateTransport();draw();};$('next-marble').onclick=()=>{const active=sim.balls.filter(b=>b.status==='active'),i=active.findIndex(b=>b.id===sim.followId);sim.followId=active[(i+1)%active.length]?.id||null;draw();};
$('trails').onclick=()=>{renderer.trails=!renderer.trails;$('trails').setAttribute('aria-pressed',String(renderer.trails));draw();};$('grid').onclick=()=>{snap=!snap;renderer.grid=snap;$('grid').setAttribute('aria-pressed',String(snap));draw();};$('sound').onclick=async()=>{if(!await chimes.toggle())notice('Audio is unavailable here. The machine still works.');$('sound').textContent=chimes.enabled?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(chimes.enabled));};
function zoom(amount){follow=false;renderer.zoom=clamp(renderer.zoom*amount,.6,3);renderer.transform();updateTransport();draw();}$('zoom-in').onclick=()=>zoom(1.25);$('zoom-out').onclick=()=>zoom(.8);$('fit').onclick=()=>{follow=false;renderer.fit();updateTransport();draw();};
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await $('lab-stage').requestFullscreen();}catch{notice('Fullscreen is unavailable in this browser.');}}
$('fullscreen').onclick=fullscreen;$('undo').onclick=()=>travelHistory(true);$('redo').onclick=()=>travelHistory(false);
const canvas=$('lab-canvas');
function pointer(e){const box=canvas.getBoundingClientRect();return renderer.world(e.clientX-box.left,e.clientY-box.top);}
canvas.addEventListener('pointerdown',e=>{if(e.button!==0&&e.button!==1)return;canvas.focus();const pt=pointer(e);canvas.setPointerCapture(e.pointerId);if(e.shiftKey||e.button===1){follow=false;drag={pan:true,x:e.clientX,y:e.clientY,cx:renderer.cx,cy:renderer.cy};return;}const hit=renderer.hit(machine,pt.x,pt.y);if(hit!==null){selected=hit;const p=hit==='source'?machine.source:piece();refresh();if(p.locked||hit==='source'&&machine.challenge){notice('This challenge piece is fixed.');return;}drag={id:hit,before:clone(machine),dx:pt.x-p.x,dy:pt.y-p.y,moved:false,startX:e.clientX,startY:e.clientY};}else{cursor=point(pt.x,pt.y);add(pt.x,pt.y);}draw();});
canvas.addEventListener('pointermove',e=>{const pt=pointer(e);hover=point(pt.x,pt.y);if(drag?.pan){renderer.cx=clamp(drag.cx-(e.clientX-drag.x)/renderer.scale,0,W);renderer.cy=clamp(drag.cy-(e.clientY-drag.y)/renderer.scale,0,H);renderer.transform();}else if(drag){if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>3){if(!drag.moved){sim.reset(machine);chimes.silence();follow=false;}drag.moved=true;const p=drag.id==='source'?machine.source:piece(),pos=point(pt.x-drag.dx,pt.y-drag.dy);if(drag.id==='source')pos.y=Math.min(pos.y,H-60);p.x=pos.x;p.y=pos.y;}}draw();});
function endDrag(e){if(!drag)return;const d=drag;drag=null;if(d.before&&d.moved)remember(d.before);if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);}
canvas.addEventListener('pointerup',endDrag);canvas.addEventListener('pointercancel',e=>{if(drag?.before){machine=drag.before;resetRun();refresh();}drag=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);});canvas.addEventListener('pointerleave',()=>{hover=null;draw();});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?1.1:1/1.1);},{passive:false});
canvas.addEventListener('keydown',e=>{
    if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();travelHistory(!e.shiftKey);return;}
    if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();cursor=point(cursor.x+(e.key==='ArrowRight'?25:e.key==='ArrowLeft'?-25:0),cursor.y+(e.key==='ArrowDown'?25:e.key==='ArrowUp'?-25:0));draw();return;}
    const k=e.key.toLowerCase();if(k==='enter'){e.preventDefault();const hit=renderer.hit(machine,cursor.x,cursor.y);if(hit!==null){selected=hit;refresh();}else add(cursor.x,cursor.y);}else if(k===' '){e.preventDefault();run();}else if(k==='a')setTool('ramp');else if(k==='v')setTool('select');else if(k==='delete'||k==='backspace'){e.preventDefault();remove();}else if(k==='d')duplicate();else if(k==='q'||k==='e'){const p=piece();if(p&&!p.locked)edit(()=>p.angle=clamp(p.angle+(k==='q'?-.087266:.087266),-Math.PI,Math.PI));}else if(k==='r'){resetRun();draw();}else if(k==='f')fullscreen();else if(k==='+'||k==='=')zoom(1.25);else if(k==='-')zoom(.8);
});
for(const [id,key,ratio] of [['angle','angle',Math.PI/180],['length','length',1],['power','power',.01]]){
    $(id).addEventListener('input',()=>{const p=piece();if(!p||p.locked)return;sliderBefore ||= clone(machine);sim.reset(machine);chimes.silence();p[key]=Number($(id).value)*ratio;$(id+'-label').textContent=id==='angle'?`${Math.round(Number($(id).value))}°`:id==='power'?p.power.toFixed(1):Math.round(p.length);draw();});
    $(id).addEventListener('change',()=>{if(sliderBefore){const before=sliderBefore;sliderBefore=null;remember(before);}});
}
$('portal-link').onchange=()=>{const p=piece(),n=Number($('portal-link').value);if(!p||p.locked)return;if(!Number.isInteger(n)||n<1||n>30||machine.pieces.filter(q=>q.type==='portal'&&q.id!==p.id&&q.link===n).length>=2){notice('Use a pair number from 1 to 30 with room for this portal.');refresh();return;}edit(()=>p.link=n);};
$('marble-count').onchange=()=>{if(machine.challenge)return;const n=Number($('marble-count').value);if(!Number.isInteger(n)||n<1||n>12){notice('Choose 1 to 12 marbles per run.');refresh();return;}edit(()=>machine.source.count=n);};$('duplicate').onclick=duplicate;$('remove-part').onclick=remove;
$('machine-name').onchange=()=>edit(()=>machine.name=$('machine-name').value.trim()||'Untitled contraption');
function shelf(){const host=$('saved-machines');host.replaceChildren();if(!saved.length){const p=document.createElement('p');p.className='empty-shelf';p.textContent='No machines saved. Keep an experiment worth repeating.';host.append(p);return;}saved.forEach((s,i)=>{const card=document.createElement('article'),h=document.createElement('h3'),small=document.createElement('small'),actions=document.createElement('div');h.textContent=s.name;small.textContent=`${s.pieces.length} parts · ${s.challenge?challenges[s.challenge].name:'Free build'}`;for(const [text,fn] of [['Open',()=>{if(confirm('Open this saved machine? This replaces your draft.'))load(clone(s),false);}],['Remove',()=>{if(!confirm(`Remove “${s.name}” from this browser?`))return;const next=saved.filter((_,n)=>n!==i);if(write(SHELF,next)){saved=next;shelf();}else notice('Storage is unavailable. Export a file to keep your machine.');}]]){const b=document.createElement('button');b.textContent=text;b.setAttribute('aria-label',`${text} ${s.name}`);b.onclick=fn;actions.append(b);}card.append(h,small,actions);host.append(card);});}
function load(s,isShared){clearTimeout(saveTimer);machine=s;shared=isShared;selected=s.pieces.find(p=>!p.locked)?.id||s.pieces[0]?.id||'source';undo=[];redo=[];resetRun();$('shared-banner').hidden=!shared;$('save-state').textContent=shared?'Shared snapshot':'Local draft';if(!shared){historyReplace();autosave();}refresh();}
function historyReplace(){if(location.hash.startsWith('#machine='))history.replaceState(null,'',location.pathname+location.search);}
function keep(){shared=false;$('shared-banner').hidden=true;historyReplace();autosave();}
$('keep-machine').onclick=()=>{keep();notice('Copy kept as your local draft.');};
$('save-machine').onclick=()=>{machine.name=$('machine-name').value.trim()||'Untitled contraption';const next=clone(saved),index=next.findIndex(s=>s.name===machine.name);if(index>=0){if(!confirm(`Replace the saved machine “${machine.name}”?`))return;next[index]=clone(machine);}else{if(next.length>=6){if(!confirm('Your six slots are full. Replace the oldest saved machine?'))return;next.shift();}next.push(clone(machine));}if(write(SHELF,next)){saved=next;keep();shelf();notice('Machine saved in this browser.');}else notice('Storage is unavailable. Export a file to keep your machine.');};
function dialog(id,trigger){const d=$(id);d.showModal();d.dataset.trigger=trigger;}
for(const id of ['share-dialog','new-dialog']){$(id).addEventListener('close',()=>$( $(id).dataset.trigger)?.focus());$(id).addEventListener('keydown',e=>{if(e.key!=='Tab')return;const nodes=[...$(id).querySelectorAll('button,input,select')].filter(n=>!n.disabled&&!n.hidden),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});}
$('share-machine').onclick=()=>{machine.name=$('machine-name').value.trim()||'Untitled contraption';const url=new URL(location.href);url.hash='machine='+encodeMachine(machine);$('share-url').value=url.href;$('copy-status').textContent='';dialog('share-dialog','share-machine');};$('copy-link').onclick=async()=>{try{await navigator.clipboard.writeText($('share-url').value);$('copy-status').textContent='Link copied.';}catch{$('share-url').focus();$('share-url').select();$('copy-status').textContent='Select the link and copy it manually.';}};
$('new-machine').onclick=()=>dialog('new-dialog','new-machine');$('create-machine').onclick=()=>{load(createMachine($('machine-template').value),false);$('new-dialog').close();};
$('mode').onchange=()=>{const target=$('mode').value;if(confirm('Switch workshop? This replaces your draft. Save first if you want to keep it.'))load(createMachine(target==='sandbox'?'starter':target),false);else $('mode').value=machine.challenge||'sandbox';};
function download(blob,extension){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=(machine.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'marble-machine')+'.'+extension;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
$('export-machine').onclick=()=>{machine.name=$('machine-name').value.trim()||'Untitled contraption';download(new Blob([JSON.stringify(machine,null,2)],{type:'application/json'}),'json');};$('import-machine').onclick=()=>$('machine-file').click();$('machine-file').onchange=async()=>{const file=$('machine-file').files[0];$('machine-file').value='';if(!file)return;if(file.size>60000){notice('Machine files must be under 60 KB.');return;}try{const s=validateMachine(JSON.parse(await file.text()));if(!s)throw Error();if(confirm('Import this machine? This replaces your draft.')){load(s,false);notice('Machine imported.');}}catch{notice('That is not a valid Marble Lab machine.');}};
$('postcard').onclick=()=>{const old={zoom:renderer.zoom,cx:renderer.cx,cy:renderer.cy};renderer.fit();renderer.draw(machine,sim,{});canvas.toBlob(blob=>{if(blob)download(blob,'png');else notice('Picture export is unavailable.');},'image/png');Object.assign(renderer,old);renderer.transform();draw();};
function readShare(){if(!location.hash.startsWith('#machine='))return;const s=decodeMachine(location.hash.slice(9));if(s)load(s,true);else notice('This machine link is invalid. Your draft is unchanged.');}
window.addEventListener('hashchange',readShare);
new ResizeObserver(()=>{renderer.resize();draw();}).observe($('lab-stage'));document.addEventListener('fullscreenchange',()=>{renderer.resize();draw();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&sim.running){sim.running=false;chimes.silence();updateTransport();}});window.addEventListener('pagehide',()=>{chimes.silence();if(!shared){clearTimeout(saveTimer);write(DRAFT,machine);}});
window.render_game_to_text=()=>JSON.stringify({coordinates:'Table units: origin top left, x right, y down. Board 1120 × 760.',name:machine.name,challenge:machine.challenge,shared,selected,tool,cursor,speed,follow,zoom:renderer.zoom,undo:undo.length,redo:redo.length,audio:{enabled:chimes.enabled,state:chimes.context?.state||'locked',strikes:chimes.strikes},source:machine.source,pieces:machine.pieces,...sim.state()});
window.advanceTime=ms=>{manual=true;let left=clamp(Number(ms)||0,0,60000)/1000*speed;while(left>0){const chunk=Math.min(left,1);sim.step(chunk);left-=chunk;}updateTransport();draw();};
window.marbleLab={snapshot:()=>clone(machine),pointScreen:(x,y)=>renderer.screen(x,y),state:()=>JSON.parse(window.render_game_to_text())};
let last=performance.now(),lastUI=0;function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;if(!manual&&!document.hidden)sim.step(dt*speed);if(now-lastUI>100){updateTransport();lastUI=now;}draw();requestAnimationFrame(frame);}
readShare();shelf();refresh();document.body.dataset.demoState='ready';requestAnimationFrame(frame);
