import {W,H,R,parts,segments,closest,clamp} from './model.js';
export class Renderer{
    constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.zoom=1;this.cx=W/2;this.cy=H/2;this.grid=false;this.trails=true;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.w=0;this.h=0;this.resize();}
    resize(){const box=this.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);this.w=box.width;this.h=box.height;this.canvas.width=Math.round(this.w*dpr);this.canvas.height=Math.round(this.h*dpr);this.dpr=dpr;this.transform();}
    transform(){this.scale=Math.min((this.w-32)/W,(this.h-32)/H)*this.zoom;this.ox=this.w/2-this.cx*this.scale;this.oy=this.h/2-this.cy*this.scale;}
    fit(){this.zoom=1;this.cx=W/2;this.cy=H/2;this.transform();}
    world(x,y){return {x:(x-this.ox)/this.scale,y:(y-this.oy)/this.scale};}
    screen(x,y){const r=this.canvas.getBoundingClientRect();return {x:r.left+this.ox+x*this.scale,y:r.top+this.oy+y*this.scale};}
    hit(machine,x,y){if(Math.hypot(x-machine.source.x,y-machine.source.y)<30)return 'source';for(const p of [...machine.pieces].reverse()){if(['ramp','belt','gate','funnel','cup','domino'].includes(p.type)){if(segments(p).some(s=>{const q=closest(x,y,s);return Math.hypot(x-q.x,y-q.y)<20;}))return p.id;if(p.type==='cup'&&Math.abs(x-p.x)<p.length/2&&Math.abs(y-p.y)<35)return p.id;}else if(Math.hypot(x-p.x,y-p.y)<p.length/2+12)return p.id;}return null;}
    line(seg,color,width){const c=this.ctx;c.beginPath();c.moveTo(seg[0],seg[1]);c.lineTo(seg[2],seg[3]);c.strokeStyle=color;c.lineWidth=width;c.lineCap='round';c.stroke();}
    draw(machine,sim,{selected,hover,tool,cursor,follow=false}={}){
        if(follow){const b=sim.balls.find(b=>b.id===sim.followId&&b.status==='active');if(b){this.zoom=2.1;this.cx=clamp(b.x,220,W-220);this.cy=clamp(b.y,170,H-170);this.transform();}}
        const c=this.ctx;c.setTransform(this.dpr,0,0,this.dpr,0,0);c.clearRect(0,0,this.w,this.h);const bg=c.createLinearGradient(0,0,this.w,this.h);bg.addColorStop(0,'#eee5d5');bg.addColorStop(1,'#e8d3bd');c.fillStyle=bg;c.fillRect(0,0,this.w,this.h);
        c.save();c.translate(this.ox,this.oy);c.scale(this.scale,this.scale);c.shadowColor='#65544128';c.shadowBlur=24;c.shadowOffsetY=10;c.fillStyle='#ddc5a4';c.beginPath();c.roundRect(-7,-7,W+14,H+22,16);c.fill();c.shadowColor='transparent';c.fillStyle='#f6ead5';c.beginPath();c.roundRect(0,0,W,H,10);c.fill();
        c.save();c.beginPath();c.roundRect(0,0,W,H,10);c.clip();for(let i=0;i<44;i++){const y=i*19;c.beginPath();c.moveTo(0,y);c.bezierCurveTo(250,y+5,750,y-6,W,y+2);c.strokeStyle=i%3?'#ac825b08':'#ac825b0d';c.lineWidth=1;c.stroke();}
        if(this.grid){c.fillStyle='#a8997d65';for(let y=25;y<H;y+=25)for(let x=25;x<W;x+=25){c.beginPath();c.arc(x,y,1.3,0,Math.PI*2);c.fill();}}
        if(this.trails)for(const b of sim.balls){if(b.trail.length<2)continue;c.beginPath();b.trail.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.strokeStyle=b.color+'55';c.lineWidth=3;c.stroke();}
        for(const p of machine.pieces)this.object(p,sim,p.id===selected);
        this.source(machine.source,selected==='source');
        if(hover&&tool!=='select'&&parts[tool]&&!sim.running){c.globalAlpha=.35;this.object({id:-1,type:tool,x:hover.x,y:hover.y,...parts[tool],link:tool==='portal'?1:0},sim,false);c.globalAlpha=1;}
        if(cursor&&!sim.running){c.strokeStyle='#5b817699';c.lineWidth=1.5;c.beginPath();c.arc(cursor.x,cursor.y,13,0,Math.PI*2);c.stroke();c.beginPath();c.moveTo(cursor.x-19,cursor.y);c.lineTo(cursor.x-10,cursor.y);c.moveTo(cursor.x+10,cursor.y);c.lineTo(cursor.x+19,cursor.y);c.stroke();}
        for(const b of sim.balls){c.save();c.translate(b.x,b.y);c.fillStyle='#6b513b22';c.beginPath();c.ellipse(3,7,10,4,0,0,Math.PI*2);c.fill();const glass=c.createRadialGradient(-3,-4,1,0,0,R+1);glass.addColorStop(0,'#fffbe9');glass.addColorStop(.28,b.color);glass.addColorStop(1,'#314e55');c.fillStyle=glass;c.beginPath();c.arc(0,0,R,0,Math.PI*2);c.fill();c.strokeStyle='#fff7ddaa';c.lineWidth=1;c.stroke();c.strokeStyle='#f1efe7aa';c.beginPath();c.arc(0,0,5,-2.5,-.5);c.stroke();c.restore();}
        for(const e of sim.effects){if(!['win','finish','catch'].includes(e.type)){const age=sim.time-e.time;c.globalAlpha=1-age/1.1;c.strokeStyle=e.type==='bell'?'#b79345':'#699d98';c.lineWidth=2;c.beginPath();c.arc(e.x,e.y,this.reduced?38:20+age*40,0,Math.PI*2);c.stroke();c.globalAlpha=1;}}
        c.restore();c.restore();
    }
    source(s,selected){const c=this.ctx;if(selected){c.strokeStyle='#4b877c';c.lineWidth=2;c.setLineDash([5,5]);c.strokeRect(s.x-30,s.y-32,60,65);c.setLineDash([]);}c.fillStyle='#b99264';c.beginPath();c.roundRect(s.x-22,s.y-30,44,42,8);c.fill();c.fillStyle='#edcca2';c.beginPath();c.ellipse(s.x,s.y-25,18,5,0,0,Math.PI*2);c.fill();for(let i=0;i<3;i++){c.fillStyle=['#6f9b9d','#c88661','#88a27a'][i];c.beginPath();c.arc(s.x-10+i*10,s.y-13,5,0,Math.PI*2);c.fill();}c.fillStyle='#756246';c.beginPath();c.roundRect(s.x-9,s.y+5,18,12,3);c.fill();c.fillStyle='#8d785b';c.font='11px system-ui';c.textAlign='center';c.fillText('RELEASE',s.x,s.y-40);}
    object(p,sim,selected){const c=this.ctx,d=parts[p.type],a=sim.dominos.get(p.id)?.angle||0;if(selected){c.save();c.strokeStyle='#4d817a';c.lineWidth=2;c.setLineDash([5,4]);if(['ramp','belt','gate','domino','funnel','cup'].includes(p.type)){for(const s of segments(p,a))this.line(s,'#4d817a',21);}else{c.beginPath();c.arc(p.x,p.y,p.length/2+9,0,Math.PI*2);c.stroke();}c.restore();}
        if(['ramp','belt','gate','domino','funnel','cup'].includes(p.type)){
            if(p.type==='gate'&&sim.gatesOpen){c.globalAlpha=.25;c.setLineDash([8,8]);}
            for(const s of segments(p,a)){this.line([s[0]+2,s[1]+7,s[2]+2,s[3]+7],'#78634e1c',13);this.line(s,p.type==='ramp'?'#be8e60':d.color,p.type==='domino'?12:11);this.line([s[0],s[1]-2,s[2],s[3]-2],p.type==='ramp'?'#ebc69b':'#f5e5c18c',2);
                if(p.type==='ramp'||p.type==='belt'){const dx=s[2]-s[0],dy=s[3]-s[1];for(const t of [.12,.88]){c.fillStyle='#e7c39a';c.beginPath();c.arc(s[0]+dx*t,s[1]+dy*t,3,0,Math.PI*2);c.fill();}}
            }c.globalAlpha=1;c.setLineDash([]);
            if(p.type==='belt'){c.save();c.translate(p.x,p.y);c.rotate(p.angle);c.strokeStyle='#f1e8c8';c.lineWidth=2;const dir=p.power<0?-1:1,phase=sim.running&&!this.reduced?(sim.time*40*dir)%25:0;for(let x=-p.length/2+20;x<p.length/2-10;x+=25){c.beginPath();c.moveTo(x+phase-dir*5,-4);c.lineTo(x+phase,0);c.lineTo(x+phase-dir*5,4);c.stroke();}c.restore();}
            if(p.type==='domino'){const s=segments(p,a)[0];c.fillStyle='#f6eace';for(const t of [.35,.65]){c.beginPath();c.arc(s[0]+(s[2]-s[0])*t,s[1]+(s[3]-s[1])*t,2,0,Math.PI*2);c.fill();}c.fillStyle='#b4a384';c.beginPath();c.arc(p.x,p.y,3,0,Math.PI*2);c.fill();}
            if(p.type==='cup'){c.fillStyle='#768b7a';c.font='11px system-ui';c.textAlign='center';c.fillText('CATCH',p.x,p.y+43);}
        }else if(p.type==='bumper'){const rad=p.length/2;c.fillStyle='#b7a88d';c.beginPath();c.arc(p.x,p.y+4,rad+3,0,Math.PI*2);c.fill();c.fillStyle=d.color;c.beginPath();c.arc(p.x,p.y,rad,0,Math.PI*2);c.fill();c.strokeStyle='#ecd2b6';c.lineWidth=3;c.beginPath();c.arc(p.x,p.y,rad*.7,0,Math.PI*2);c.stroke();c.fillStyle='#9f594e';c.beginPath();c.arc(p.x,p.y,rad*.25,0,Math.PI*2);c.fill();
        }else if(p.type==='magnet'){c.strokeStyle='#ad746347';c.lineWidth=1;c.setLineDash([4,6]);c.beginPath();c.arc(p.x,p.y,170,0,Math.PI*2);c.stroke();c.setLineDash([]);c.save();c.translate(p.x,p.y);c.rotate(p.angle);c.strokeStyle=d.color;c.lineWidth=12;c.beginPath();c.arc(0,0,p.length/3,Math.PI,0);c.lineTo(p.length/3,15);c.moveTo(-p.length/3,0);c.lineTo(-p.length/3,15);c.stroke();c.strokeStyle='#ede5d4';c.lineWidth=12;c.beginPath();c.moveTo(-p.length/3,13);c.lineTo(-p.length/3,20);c.moveTo(p.length/3,13);c.lineTo(p.length/3,20);c.stroke();c.restore();
        }else if(p.type==='portal'){const rad=p.length/2;c.strokeStyle=p.link%2?'#6b9fa1':'#b89969';c.lineWidth=5;c.beginPath();c.ellipse(p.x,p.y,rad,rad,0,0,Math.PI*2);c.stroke();c.lineWidth=1.5;c.strokeStyle='#dfcaa5';c.beginPath();c.arc(p.x,p.y,rad+5,0,Math.PI*2);c.stroke();c.fillStyle='#69928b';c.font='bold 15px system-ui';c.textAlign='center';c.fillText(String(p.link||'?'),p.x,p.y+5);c.save();c.translate(p.x,p.y);c.rotate(p.angle);c.strokeStyle='#769d96';c.lineWidth=2;c.beginPath();c.moveTo(-5,rad-5);c.lineTo(0,rad);c.lineTo(5,rad-5);c.stroke();c.restore();
        }else if(p.type==='bell'){c.fillStyle='#b09850';c.beginPath();c.moveTo(p.x-18,p.y+14);c.quadraticCurveTo(p.x-14,p.y+3,p.x-10,p.y-10);c.quadraticCurveTo(p.x,p.y-23,p.x+10,p.y-10);c.quadraticCurveTo(p.x+14,p.y+3,p.x+18,p.y+14);c.closePath();c.fill();c.strokeStyle='#d3b975';c.lineWidth=2;c.beginPath();c.moveTo(p.x-18,p.y+14);c.lineTo(p.x+18,p.y+14);c.stroke();c.fillStyle='#8a743d';c.beginPath();c.arc(p.x,p.y+17,4,0,Math.PI*2);c.fill();c.strokeStyle='#a59165';c.lineWidth=2;c.beginPath();c.arc(p.x,p.y-20,4,Math.PI,0);c.stroke();
        }else if(p.type==='switch'){c.fillStyle=sim.gatesOpen?'#72947c':'#b5aa8b';c.beginPath();c.arc(p.x,p.y,p.length/2,0,Math.PI*2);c.fill();c.fillStyle='#f1e6ca';c.beginPath();c.arc(p.x,p.y,p.length/3,0,Math.PI*2);c.fill();c.strokeStyle='#6d8973';c.lineWidth=3;c.beginPath();c.moveTo(p.x,p.y+6);c.lineTo(p.x+(sim.gatesOpen?10:-10),p.y-8);c.stroke();}
        if(p.locked){c.fillStyle='#7e7e6888';c.font='11px system-ui';c.textAlign='center';c.fillText('FIXED',p.x,p.y+(p.type==='gate'?24:p.type==='cup'?58:36));}
    }
}
